//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountCustomer()
        {
            this.AccountCustomerDetails = new HashSet<AccountCustomerDetail>();
            this.NobatDetail5 = new HashSet<NobatDetail5>();
        }
    
        public decimal ID_account_customer { get; set; }
        public Nullable<decimal> id_illness { get; set; }
        public Nullable<int> id_statuscard { get; set; }
        public string takhasos { get; set; }
        public string id_alarm { get; set; }
        public string comment { get; set; }
        public Nullable<int> id_priority_nobat { get; set; }
        public string Date_edit { get; set; }
    
        public virtual AccountCustomerMax AccountCustomerMax { get; set; }
        public virtual InfoSick InfoSick { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountCustomerDetail> AccountCustomerDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NobatDetail5> NobatDetail5 { get; set; }
    }
}
