//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_change_protocol
    {
        public decimal idauto { get; set; }
        public Nullable<byte> flag { get; set; }
        public Nullable<byte> id_software { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> kindid { get; set; }
        public string date_edit { get; set; }
        public string time_edit { get; set; }
        public Nullable<bool> flag_tamdid { get; set; }
    }
}
