//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class aghsat_detail
    {
        public decimal kindid { get; set; }
        public decimal rowid { get; set; }
        public string date_pardakht { get; set; }
        public Nullable<decimal> mab_pardakhti { get; set; }
        public string date_edit { get; set; }
        public string time_edit { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public Nullable<decimal> mab_ghabel_daryaft { get; set; }
        public string date_ghest { get; set; }
        public Nullable<decimal> code_bank { get; set; }
        public Nullable<decimal> code_shobe { get; set; }
        public Nullable<byte> flag_vosol { get; set; }
        public string date_resid { get; set; }
        public Nullable<decimal> mab_checkfish { get; set; }
        public Nullable<decimal> checkfish_no { get; set; }
        public string date_edit_vosol { get; set; }
        public string time_edit_vosol { get; set; }
        public Nullable<decimal> id_user_vosol { get; set; }
        public string date_vosol_back { get; set; }
        public string time_vosol_back { get; set; }
        public Nullable<decimal> id_user_vosol_back { get; set; }
        public Nullable<bool> FLag_Send_Cash { get; set; }
        public Nullable<decimal> RecNo_Cash { get; set; }
    }
}
