//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class amval
    {
        public decimal Idauto { get; set; }
        public string titlegoods { get; set; }
        public string Mkeep { get; set; }
        public string motasadi { get; set; }
        public string dat_tolid { get; set; }
        public string dat_kharid { get; set; }
        public string useful { get; set; }
        public string SN_Fani { get; set; }
        public string Constructor { get; set; }
        public string BackUp_CO { get; set; }
        public string Zemanat { get; set; }
        public string Khadamat { get; set; }
        public string Status { get; set; }
        public string KindKharid { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string name_user { get; set; }
        public string date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<int> CenterID { get; set; }
    
        public virtual infoCenteral infoCenteral { get; set; }
    }
}
