//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Antibiotic
    {
        public decimal Code { get; set; }
        public decimal RowID { get; set; }
        public int CenterID { get; set; }
        public string descript { get; set; }
        public Nullable<decimal> IDSub { get; set; }
        public Nullable<decimal> idindex { get; set; }
        public Nullable<int> CurrentRow { get; set; }
        public Nullable<bool> Checked { get; set; }
        public string NodePtr { get; set; }
        public Nullable<int> fix { get; set; }
        public Nullable<decimal> id_User { get; set; }
        public string Date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<System.DateTime> date_Edit_M { get; set; }
        public Nullable<System.DateTime> Date_Delete { get; set; }
        public Nullable<decimal> Id_UserDelete { get; set; }
        public Nullable<int> ID_software { get; set; }
        public Nullable<decimal> Cancel_Flag { get; set; }
    
        public virtual infoCenteral infoCenteral { get; set; }
    }
}
