//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class assessment
    {
        public decimal Idauto { get; set; }
        public Nullable<decimal> Idtash { get; set; }
        public Nullable<decimal> id_visit { get; set; }
        public string dat_visit { get; set; }
        public Nullable<decimal> id_sick { get; set; }
        public string daro { get; set; }
        public string command { get; set; }
        public string dat { get; set; }
        public Nullable<decimal> id_service { get; set; }
        public string noskheh { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string name_user { get; set; }
        public string date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<int> CenterID { get; set; }
    }
}
