//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthUser
    {
        public decimal UserCode { get; set; }
        public int id_software { get; set; }
        public int Code { get; set; }
        public int CenterID { get; set; }
        public Nullable<bool> Show { get; set; }
        public Nullable<bool> ins { get; set; }
        public Nullable<bool> Edit { get; set; }
        public Nullable<bool> del { get; set; }
        public Nullable<bool> DesignPrint { get; set; }
        public Nullable<bool> other { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string date_edit { get; set; }
        public string time_edit { get; set; }
    
        public virtual infoCenteral infoCenteral { get; set; }
        public virtual InfoSoftware InfoSoftware { get; set; }
        public virtual Infouser Infouser { get; set; }
    }
}
