//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank_Detail
    {
        public int ID_Shobe { get; set; }
        public Nullable<int> Code { get; set; }
        public string Descript { get; set; }
        public string Shakhes { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Comment { get; set; }
    }
}
