//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basicinfo
    {
        public decimal BasicinfoKindID { get; set; }
        public decimal Code { get; set; }
        public decimal RowID { get; set; }
        public Nullable<byte> AccessID { get; set; }
        public string Codemanual { get; set; }
        public Nullable<int> CenterID { get; set; }
        public string descript { get; set; }
        public string NameMenu { get; set; }
        public Nullable<decimal> CodeInternational { get; set; }
        public Nullable<decimal> IDSub { get; set; }
        public Nullable<decimal> idindex { get; set; }
        public Nullable<int> CurrentRow { get; set; }
        public Nullable<bool> Checked { get; set; }
        public string NodePtr { get; set; }
        public Nullable<int> fix { get; set; }
        public Nullable<decimal> id_User { get; set; }
        public string Date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<System.DateTime> date_Edit_M { get; set; }
        public Nullable<System.DateTime> Date_Delete { get; set; }
        public Nullable<decimal> Id_UserDelete { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string doctorID { get; set; }
        public Nullable<decimal> ID_takhasos { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public Nullable<int> vahedid { get; set; }
        public string cashplace { get; set; }
        public string cashIP { get; set; }
        public string D_Run { get; set; }
        public string D_Expire { get; set; }
        public Nullable<int> ID_software { get; set; }
        public string UserAccess { get; set; }
        public Nullable<int> Cancel_Flag { get; set; }
        public string Cancel_FlagDate { get; set; }
        public string City { get; set; }
        public string TaminIDTypeDoc { get; set; }
        public string TaminIDTakhasos { get; set; }
    }
}
