//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasicinfoKind
    {
        public decimal BasicinfoKindID { get; set; }
        public string descript { get; set; }
        public Nullable<int> IDSoftWare { get; set; }
        public Nullable<decimal> tabsheet { get; set; }
        public string TableName { get; set; }
        public Nullable<int> CenterID { get; set; }
        public Nullable<int> OrderField { get; set; }
        public Nullable<int> Sorting { get; set; }
    
        public virtual infoCenteral infoCenteral { get; set; }
    }
}
