//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beyaneh
    {
        public decimal idauto { get; set; }
        public Nullable<decimal> id_sick { get; set; }
        public string D_Save { get; set; }
        public Nullable<int> Flag { get; set; }
        public Nullable<decimal> Mab_Beyaneh { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string date_Edit { get; set; }
        public string time_Edit { get; set; }
        public string comment { get; set; }
        public Nullable<int> CenterID { get; set; }
        public Nullable<int> id_software { get; set; }
        public Nullable<int> RecNo { get; set; }
        public Nullable<byte> PrintCount { get; set; }
        public Nullable<int> id_section { get; set; }
    
        public virtual infoCenteral infoCenteral { get; set; }
    }
}
