//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class block_illness
    {
        public decimal kindid { get; set; }
        public Nullable<decimal> id_illness { get; set; }
        public string date_block { get; set; }
        public string descript { get; set; }
        public Nullable<bool> @default { get; set; }
        public Nullable<decimal> id_software { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public Nullable<int> centerid { get; set; }
        public string date_edit { get; set; }
        public string time_edit { get; set; }
        public Nullable<bool> varning_free { get; set; }
    
        public virtual infoCenteral infoCenteral { get; set; }
    }
}
