//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calculate_Before_free_insur
    {
        public decimal ID { get; set; }
        public Nullable<decimal> id_insur1 { get; set; }
        public Nullable<decimal> id_insur2 { get; set; }
        public Nullable<int> id_software { get; set; }
        public string D_run { get; set; }
        public string D_expire { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string Date_edit { get; set; }
        public string Time_edit { get; set; }
        public Nullable<decimal> id_niro { get; set; }
        public Nullable<decimal> id_nesbat { get; set; }
        public Nullable<decimal> id_status { get; set; }
        public Nullable<decimal> code_rule { get; set; }
    
        public virtual InfoSoftware InfoSoftware { get; set; }
        public virtual Infouser Infouser { get; set; }
        public virtual infonesbat infonesbat { get; set; }
        public virtual infoniro infoniro { get; set; }
        public virtual InfoStatu InfoStatu { get; set; }
        public virtual insur insur { get; set; }
        public virtual insur insur1 { get; set; }
    }
}
