//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalenderMaster1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CalenderMaster1()
        {
            this.CalenderDetail_Day1 = new HashSet<CalenderDetail_Day1>();
            this.CalenderDetail_Section1 = new HashSet<CalenderDetail_Section1>();
        }
    
        public decimal ID { get; set; }
        public Nullable<int> CenterID { get; set; }
        public Nullable<decimal> id_doctor { get; set; }
        public Nullable<decimal> From_Date { get; set; }
        public Nullable<decimal> To_Date { get; set; }
        public string From_Time { get; set; }
        public string To_Time { get; set; }
        public Nullable<int> Count_Addi { get; set; }
        public Nullable<int> Count_Modir { get; set; }
        public Nullable<int> Count_All { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string date_edit { get; set; }
        public string time_edit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalenderDetail_Day1> CalenderDetail_Day1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalenderDetail_Section1> CalenderDetail_Section1 { get; set; }
        public virtual infoCenteral infoCenteral { get; set; }
        public virtual Infodentist Infodentist { get; set; }
        public virtual Infouser Infouser { get; set; }
    }
}
