//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class cause_delete
    {
        public decimal RowID { get; set; }
        public decimal Code { get; set; }
        public string descript { get; set; }
        public Nullable<int> CenterID { get; set; }
        public Nullable<decimal> ID_Software { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string date_delete { get; set; }
        public string Time_delete { get; set; }
        public Nullable<decimal> id_userDelete { get; set; }
        public Nullable<decimal> Idauto { get; set; }
    
        public virtual infoCenteral infoCenteral { get; set; }
    }
}
