//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class CenterSoftwarePeyGiri
    {
        public decimal ID { get; set; }
        public Nullable<int> CenterID { get; set; }
        public string DatePeygiri { get; set; }
        public string TimePeygiri { get; set; }
        public Nullable<decimal> id_User_SendTo { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> SendOK { get; set; }
        public string Date_Send { get; set; }
        public string Time_Send { get; set; }
        public Nullable<byte> CurrentRow { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string date_edit { get; set; }
        public string time_edit { get; set; }
        public Nullable<int> Delivered { get; set; }
    
        public virtual infoCenteral infoCenteral { get; set; }
        public virtual Infouser Infouser { get; set; }
        public virtual Infouser Infouser1 { get; set; }
    }
}
