//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class change_after_use
    {
        public decimal kindid { get; set; }
        public decimal id_user { get; set; }
        public string date_edit { get; set; }
        public string time_edit { get; set; }
        public Nullable<decimal> id_section { get; set; }
        public Nullable<byte> id_software { get; set; }
        public Nullable<bool> @checked { get; set; }
        public Nullable<byte> flag { get; set; }
    }
}
