//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefineHazinenoskheh
    {
        public decimal RowID { get; set; }
        public decimal ID_SoftWare { get; set; }
        public decimal vahedid { get; set; }
        public decimal Code { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public decimal CurrentRow { get; set; }
        public Nullable<decimal> ID_User { get; set; }
        public string Date_Edit { get; set; }
        public string Date_Edit_M { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<int> Cancel_Flag { get; set; }
        public Nullable<decimal> idauto { get; set; }
        public Nullable<decimal> Id_UserDelete { get; set; }
        public Nullable<System.DateTime> Date_Delete { get; set; }
        public Nullable<decimal> priceIndexcripday { get; set; }
        public Nullable<decimal> priceIndexcripnight { get; set; }
        public Nullable<decimal> maxcurrhagfanday { get; set; }
        public Nullable<decimal> maxcurrhagfannight { get; set; }
        public Nullable<decimal> mincurrhagfanday { get; set; }
        public Nullable<decimal> mincurrhagfannight { get; set; }
        public Nullable<decimal> maxcurrOTC { get; set; }
        public Nullable<decimal> percentCurrOTC { get; set; }
        public Nullable<decimal> currwriteInsur { get; set; }
        public Nullable<decimal> hazinehpackfree { get; set; }
        public string timeDayfrom { get; set; }
        public string timedayto { get; set; }
        public string timenightfrom { get; set; }
        public string timenightto { get; set; }
        public Nullable<decimal> moafhaghfaninight { get; set; }
        public Nullable<decimal> moafhaghfaniday { get; set; }
        public Nullable<decimal> maxcurrOTCnight { get; set; }
        public Nullable<decimal> percentcurrOTCnight { get; set; }
        public Nullable<decimal> id_insur { get; set; }
        public Nullable<double> per_illness { get; set; }
        public Nullable<double> per_org { get; set; }
        public Nullable<double> minPerhagfanday { get; set; }
        public Nullable<double> maxPerhagfanday { get; set; }
        public Nullable<double> minPerhagfannight { get; set; }
        public Nullable<double> maxPerhagfannight { get; set; }
        public Nullable<decimal> Roof_minCurrhagfanday { get; set; }
        public Nullable<decimal> Roof_maxCurrhagfanday { get; set; }
        public Nullable<decimal> Roof_minCurrhagfannight { get; set; }
        public Nullable<decimal> Roof_maxCurrhagfannight { get; set; }
    }
}
