//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Define_AccountNo
    {
        public int ID_ { get; set; }
        public Nullable<int> Bank_Code { get; set; }
        public Nullable<int> ID_ShobeRel { get; set; }
        public string AccountName { get; set; }
        public string AccountNo { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Time_Edit { get; set; }
        public string Date_Edit { get; set; }
        public Nullable<int> ID_User { get; set; }
    }
}
