//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class defultsoft
    {
        public int code { get; set; }
        public Nullable<decimal> id_insur { get; set; }
        public Nullable<decimal> id_nesbat { get; set; }
        public Nullable<decimal> id_niro { get; set; }
        public Nullable<decimal> id_status { get; set; }
        public Nullable<int> CenterID { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public Nullable<decimal> ID_Software { get; set; }
        public string date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<decimal> Idauto { get; set; }
        public string descript { get; set; }
    
        public virtual infoCenteral infoCenteral { get; set; }
    }
}
