//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class descript_section
    {
        public decimal kindid { get; set; }
        public Nullable<decimal> id_section { get; set; }
        public string descript { get; set; }
        public string space_descript { get; set; }
    }
}
