//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class detailLab
    {
        public decimal id_sick { get; set; }
        public int Radif { get; set; }
        public string date_eraeh { get; set; }
        public string date_tahvil { get; set; }
        public Nullable<int> id_user { get; set; }
        public int idHazineh { get; set; }
        public Nullable<int> CenterID { get; set; }
    
        public virtual infoCenteral infoCenteral { get; set; }
    }
}
