//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailKharid
    {
        public decimal CodeSyskharid { get; set; }
        public decimal RowID { get; set; }
        public decimal ID_SoftWare { get; set; }
        public decimal vahedid { get; set; }
        public Nullable<decimal> Codesys { get; set; }
        public decimal CurrentRow { get; set; }
        public Nullable<decimal> ID_User { get; set; }
        public string Date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<int> Cancel_Flag { get; set; }
        public Nullable<decimal> idauto { get; set; }
        public Nullable<decimal> Id_UserDelete { get; set; }
        public Nullable<System.DateTime> Date_Delete { get; set; }
        public string CodeKharid { get; set; }
        public string Date_Kharid { get; set; }
        public Nullable<decimal> CodeCompany { get; set; }
        public decimal CodeGoods { get; set; }
        public string CommentGoods { get; set; }
        public Nullable<decimal> CountGoods { get; set; }
        public Nullable<decimal> CountTempMojodi { get; set; }
        public Nullable<decimal> CurrKharid { get; set; }
        public string Date_Run { get; set; }
        public string Date_Expire { get; set; }
        public Nullable<decimal> CurrAll { get; set; }
        public string Comment { get; set; }
        public Nullable<decimal> flageditedDetail { get; set; }
        public Nullable<decimal> KindbargashtGoods { get; set; }
        public string date_Bargasht { get; set; }
        public Nullable<decimal> codepaziresh { get; set; }
        public Nullable<decimal> mainGroupGoods { get; set; }
        public Nullable<int> id_oodat { get; set; }
        public Nullable<decimal> code_anbar { get; set; }
        public Nullable<decimal> CountGoods_off { get; set; }
        public Nullable<decimal> CountGoods_on { get; set; }
    }
}
