//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceLab_Hitachi911Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeviceLab_Hitachi911Master()
        {
            this.DeviceLab_Hitachi911Detail = new HashSet<DeviceLab_Hitachi911Detail>();
        }
    
        public decimal ID { get; set; }
        public Nullable<int> CenterID { get; set; }
        public string DeviceName { get; set; }
        public string Port { get; set; }
        public string ConnectionPort { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string Date_Edit { get; set; }
        public string Time_Edit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceLab_Hitachi911Detail> DeviceLab_Hitachi911Detail { get; set; }
        public virtual Infouser Infouser { get; set; }
    }
}
