//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceLab_sysmexkn21Detail
    {
        public decimal ID { get; set; }
        public Nullable<decimal> ID_DeviceLab_sysmexkn21Master { get; set; }
        public Nullable<decimal> id_Service_Rozaneh { get; set; }
        public Nullable<decimal> Num_div { get; set; }
        public Nullable<int> Rowidsort { get; set; }
        public Nullable<decimal> Num_mul { get; set; }
    
        public virtual DeviceLab_sysmexkn21Master DeviceLab_sysmexkn21Master { get; set; }
        public virtual InfoTest InfoTest { get; set; }
    }
}
