//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctorType
    {
        public int Code { get; set; }
        public int CenterID { get; set; }
        public Nullable<int> idsub { get; set; }
        public string descript { get; set; }
        public string NodePtr { get; set; }
        public Nullable<bool> fix { get; set; }
        public Nullable<bool> Checked { get; set; }
        public Nullable<int> id_user { get; set; }
        public string date_edit { get; set; }
        public string time_edit { get; set; }
    }
}
