//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctor7
    {
        public decimal code { get; set; }
        public Nullable<decimal> codemanual { get; set; }
        public string code_nezam { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<decimal> id_takhasos { get; set; }
        public Nullable<decimal> code_karbari { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string date_edit { get; set; }
        public string time_edit { get; set; }
        public Nullable<int> id_level_takhasos { get; set; }
        public Nullable<int> mis_code { get; set; }
    }
}
