//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.FamilyReferMasters = new HashSet<FamilyReferMaster>();
            this.Paziresh3 = new HashSet<Paziresh3>();
            this.Paziresh31 = new HashSet<Paziresh3>();
        }
    
        public int Code { get; set; }
        public string CodeNezam { get; set; }
        public int CenterID { get; set; }
        public int id_software { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string tel { get; set; }
        public Nullable<int> ID_takhasos { get; set; }
        public string address { get; set; }
        public string City { get; set; }
        public string time_edit { get; set; }
        public string date_edit { get; set; }
        public int id_user { get; set; }
        public string nodeptr { get; set; }
        public Nullable<bool> @checked { get; set; }
        public Nullable<decimal> idgroup { get; set; }
        public Nullable<byte> id_level { get; set; }
        public string sex { get; set; }
        public Nullable<int> id_Person { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FamilyReferMaster> FamilyReferMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paziresh3> Paziresh3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paziresh3> Paziresh31 { get; set; }
    }
}
