//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctor_not_hozor
    {
        public decimal kindid { get; set; }
        public Nullable<int> id_software { get; set; }
        public string date_not_hozor { get; set; }
        public Nullable<decimal> id_doctor { get; set; }
        public string comment { get; set; }
        public string date_edit { get; set; }
        public string time_edit { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public Nullable<int> CenterID { get; set; }
        public Nullable<bool> Flag_time { get; set; }
        public string Fromtime { get; set; }
        public string Totime { get; set; }
    }
}
