//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor_Days
    {
        public int RuleID { get; set; }
        public int RowID { get; set; }
        public Nullable<decimal> doctorid { get; set; }
        public string F_time { get; set; }
        public string T_time { get; set; }
        public string F_date { get; set; }
        public string T_date { get; set; }
        public Nullable<decimal> WorkTime { get; set; }
        public Nullable<byte> Days { get; set; }
        public Nullable<int> id_user { get; set; }
        public string date_edit { get; set; }
        public string time_edit { get; set; }
        public Nullable<bool> Checked { get; set; }
        public int id_software { get; set; }
        public Nullable<decimal> id_section { get; set; }
        public Nullable<int> count_nobat { get; set; }
        public Nullable<decimal> nobat_modiriyati { get; set; }
        public Nullable<decimal> count_nobat_modiriyati { get; set; }
    }
}
