//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class erjaillnessdetail
    {
        public decimal kindid { get; set; }
        public decimal rowid { get; set; }
        public Nullable<decimal> id_section { get; set; }
        public string comment { get; set; }
        public string d1 { get; set; }
        public string d2 { get; set; }
        public string d3 { get; set; }
        public string d4 { get; set; }
        public Nullable<int> CenterID { get; set; }
        public Nullable<decimal> currentrow { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public Nullable<byte> Cancel_Flag { get; set; }
        public string date_delete { get; set; }
        public Nullable<decimal> id_userDelete { get; set; }
        public Nullable<decimal> Idauto { get; set; }
        public Nullable<bool> ErjaOK { get; set; }
    }
}
