//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ezam
    {
        public decimal kindid { get; set; }
        public Nullable<decimal> id_illness { get; set; }
        public string date_ezam { get; set; }
        public Nullable<decimal> to_ezam { get; set; }
        public string ezam_comment { get; set; }
    }
}
