//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyStructureTableMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FamilyStructureTableMaster()
        {
            this.FamilyStructureTableDetails = new HashSet<FamilyStructureTableDetail>();
        }
    
        public decimal ID { get; set; }
        public string Header { get; set; }
        public string TableName { get; set; }
        public string FileNameXML { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FamilyStructureTableDetail> FamilyStructureTableDetails { get; set; }
    }
}
