//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyDoctorDetail_LabResult
    {
        public decimal ID { get; set; }
        public Nullable<decimal> ID_FamilyDoctorDetail_Lab { get; set; }
        public string Result { get; set; }
        public string UnitName { get; set; }
        public string NormalRange { get; set; }
        public string LowHighResult { get; set; }
        public string ReCheck { get; set; }
    
        public virtual FamilyDoctorDetail_Lab FamilyDoctorDetail_Lab { get; set; }
    }
}
