//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyStructureTableDetail
    {
        public decimal ID { get; set; }
        public decimal ID_FamilyStructureTableMaster { get; set; }
        public string FieldName { get; set; }
        public string DataType { get; set; }
        public Nullable<int> LenField { get; set; }
        public string descript { get; set; }
    
        public virtual FamilyStructureTableMaster FamilyStructureTableMaster { get; set; }
    }
}
