//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyReferMaster
    {
        public decimal ID { get; set; }
        public string CodeRefer { get; set; }
        public string dateRefer { get; set; }
        public Nullable<int> validDay { get; set; }
        public string DiagFamilyDoctor { get; set; }
        public string CommentFamilyDoctor { get; set; }
        public Nullable<int> id_doctor_ReferTo { get; set; }
        public Nullable<decimal> ID_User { get; set; }
        public string Date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<decimal> id_illness { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Infouser Infouser { get; set; }
    }
}
