//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyDoctorInfo
    {
        public decimal ID { get; set; }
        public string CodeNezam { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string Takhasos { get; set; }
        public string UID { get; set; }
        public string PID { get; set; }
        public Nullable<int> id_person { get; set; }
    }
}
