//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyReferDetail
    {
        public decimal ID { get; set; }
        public Nullable<decimal> ID_CodeRefer { get; set; }
        public string DiagReferDoctor { get; set; }
        public string CommentReferDoctor { get; set; }
        public string CommentReferDoctorMazad { get; set; }
        public string NextDate { get; set; }
        public Nullable<decimal> ID_User { get; set; }
        public string Date_Edit { get; set; }
        public string Time_Edit { get; set; }
    
        public virtual Infouser Infouser { get; set; }
    }
}
