//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class frmPerson_Maliyat
    {
        public decimal ID { get; set; }
        public string Name { get; set; }
        public string num_eghtesad { get; set; }
        public string mellicode { get; set; }
        public string ostan { get; set; }
        public string shahrestan { get; set; }
        public string code_posti { get; set; }
        public string city { get; set; }
        public string tel { get; set; }
        public string address { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string date_edit { get; set; }
        public string time_edit { get; set; }
    }
}
