//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Good
    {
        public decimal ID_SoftWare { get; set; }
        public decimal Code { get; set; }
        public decimal RowID { get; set; }
        public decimal vahedid { get; set; }
        public decimal CurrentRow { get; set; }
        public Nullable<decimal> ID_User { get; set; }
        public string Date_Edit { get; set; }
        public Nullable<System.DateTime> Date_Edit_M { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<int> Cancel_Flag { get; set; }
        public Nullable<decimal> idauto { get; set; }
        public Nullable<decimal> Id_UserDelete { get; set; }
        public Nullable<System.DateTime> Date_Delete { get; set; }
        public string CodeNational { get; set; }
        public string LatinTitle { get; set; }
        public string FarsiTitle { get; set; }
        public string TejariTitle { get; set; }
        public string EkhtesariTitle { get; set; }
        public Nullable<decimal> Id_Unit { get; set; }
        public Nullable<decimal> Id_shape { get; set; }
        public Nullable<decimal> Id_MainGroup { get; set; }
        public Nullable<decimal> Id_MirorGroup { get; set; }
        public Nullable<decimal> id_SintificGroup { get; set; }
        public Nullable<bool> Is_OTC { get; set; }
        public Nullable<bool> Is_HagFan { get; set; }
        public Nullable<bool> Is_pezpub { get; set; }
        public Nullable<bool> Is_pezpri { get; set; }
        public Nullable<bool> Is_mama { get; set; }
        public string id_Pezeshk { get; set; }
        public Nullable<decimal> MaxSale { get; set; }
        public Nullable<decimal> MinSale { get; set; }
        public Nullable<decimal> Mojodi { get; set; }
        public string barcode { get; set; }
        public Nullable<int> sarpa_bastari { get; set; }
        public Nullable<decimal> CountDefault { get; set; }
        public Nullable<decimal> DotOrder { get; set; }
        public Nullable<bool> Checked { get; set; }
        public string dose { get; set; }
        public Nullable<decimal> codemanual { get; set; }
        public Nullable<int> mis_code { get; set; }
        public Nullable<int> ID_KarServiceGrp { get; set; }
    }
}
