//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISFamilyDocBaseSex
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HISFamilyDocBaseSex()
        {
            this.HISFamilyDocQuesionDetailSexes = new HashSet<HISFamilyDocQuesionDetailSex>();
        }
    
        public byte Code { get; set; }
        public string NameSex { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISFamilyDocQuesionDetailSex> HISFamilyDocQuesionDetailSexes { get; set; }
    }
}
