//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holiday
    {
        public string dat { get; set; }
        public decimal RowID { get; set; }
        public int CenterID { get; set; }
        public decimal ID_Software { get; set; }
        public Nullable<decimal> ID_User { get; set; }
        public Nullable<decimal> CurrentRow { get; set; }
        public string Date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<System.DateTime> date_Edit_M { get; set; }
        public Nullable<System.DateTime> Date_Delete { get; set; }
        public Nullable<decimal> Id_UserDelete { get; set; }
        public Nullable<decimal> vahedid_Delete { get; set; }
    
        public virtual infoCenteral infoCenteral { get; set; }
    }
}
