//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class IllnessFileMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IllnessFileMaster()
        {
            this.IllnessFileDetails = new HashSet<IllnessFileDetail>();
        }
    
        public decimal ID { get; set; }
        public Nullable<int> CenterID { get; set; }
        public decimal id_illness { get; set; }
        public Nullable<int> id_state { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IllnessFileDetail> IllnessFileDetails { get; set; }
        public virtual infoCenteral infoCenteral { get; set; }
        public virtual InfoSick InfoSick { get; set; }
    }
}
