//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class IllnessFileRequest
    {
        public decimal ID { get; set; }
        public Nullable<int> CenterID { get; set; }
        public Nullable<decimal> id_Illness { get; set; }
        public Nullable<decimal> Date_Request { get; set; }
        public Nullable<bool> Response { get; set; }
        public Nullable<decimal> id_user_Response { get; set; }
        public Nullable<decimal> date_Edit_Response { get; set; }
        public string Time_Edit_Response { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<byte> Flag_Cancel { get; set; }
        public Nullable<decimal> id_User_Cancel { get; set; }
        public string Date_Edir_Cancel { get; set; }
        public string Time_Edit_Cancel { get; set; }
    
        public virtual infoCenteral infoCenteral { get; set; }
        public virtual InfoSick InfoSick { get; set; }
        public virtual Infouser Infouser { get; set; }
        public virtual Infouser Infouser1 { get; set; }
    }
}
