//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class IllnessHistory_Detail1
    {
        public decimal id_sick { get; set; }
        public Nullable<int> RowID { get; set; }
        public decimal id_systemic_illness { get; set; }
    
        public virtual InfoSystem InfoSystem { get; set; }
        public virtual InfoSick InfoSick { get; set; }
    }
}
