//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class IllnessHistory_Past
    {
        public decimal id_illness { get; set; }
        public decimal id_systemic_past { get; set; }
        public string comment { get; set; }
        public string date_edit { get; set; }
        public string time_edit { get; set; }
        public Nullable<decimal> id_user { get; set; }
    
        public virtual InfoSick InfoSick { get; set; }
        public virtual Infouser Infouser { get; set; }
        public virtual infopast_history infopast_history { get; set; }
    }
}
