//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoCompanyDetail2
    {
        public decimal ID { get; set; }
        public Nullable<decimal> IDInfoCompanyDetail2 { get; set; }
        public string SN1 { get; set; }
        public string SN2 { get; set; }
        public string SN3 { get; set; }
        public string Date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_User_install_Support { get; set; }
    
        public virtual InfoCompanyDetail1 InfoCompanyDetail1 { get; set; }
    }
}
