//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoSick
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InfoSick()
        {
        //    this.AccountCustomers = new HashSet<AccountCustomer>();
        //    this.AccountCustomerDetails = new HashSet<AccountCustomerDetail>();
        //    this.FamilyDoctorMasters = new HashSet<FamilyDoctorMaster>();
        //    this.Hazineh2 = new HashSet<Hazineh2>();
        //    this.HISFamilyDocResponseDetails = new HashSet<HISFamilyDocResponseDetail>();
        //    this.IllnessFileMasters = new HashSet<IllnessFileMaster>();
        //    this.IllnessFileRequests = new HashSet<IllnessFileRequest>();
        //    this.IllnessHistory_Compliant = new HashSet<IllnessHistory_Compliant>();
        //    this.IllnessHistory_Detail1 = new HashSet<IllnessHistory_Detail1>();
        //    this.IllnessHistory_Detail2 = new HashSet<IllnessHistory_Detail2>();
        //    this.IllnessHistory_Detail3 = new HashSet<IllnessHistory_Detail3>();
        //    this.IllnessHistory_Drug_Interaction = new HashSet<IllnessHistory_Drug_Interaction>();
        //    this.IllnessHistory_Drug_Use = new HashSet<IllnessHistory_Drug_Use>();
        //    this.IllnessHistory_Family = new HashSet<IllnessHistory_Family>();
        //    this.IllnessHistory_Past = new HashSet<IllnessHistory_Past>();
        //    this.infosick_detail = new HashSet<infosick_detail>();
        //    this.NobatDetail5 = new HashSet<NobatDetail5>();
        //    this.Paziresh2 = new HashSet<Paziresh2>();
        //    this.Paziresh3 = new HashSet<Paziresh3>();
        //    this.Paziresh4 = new HashSet<Paziresh4>();
        //    this.Paziresh8 = new HashSet<Paziresh8>();
        //    this.Rulesaghf_baharan_master = new HashSet<Rulesaghf_baharan_master>();
        //    this.RuleSaghfFardi1 = new HashSet<RuleSaghfFardi1>();
        //    this.RuleSaghfFardi2 = new HashSet<RuleSaghfFardi2>();
        //    this.RuleSaghfFardi4 = new HashSet<RuleSaghfFardi4>();
        //    this.RuleSaghfFardi5 = new HashSet<RuleSaghfFardi5>();
        //    this.visitings = new HashSet<visiting>();
        }
    
        public decimal IDsick { get; set; }
        public Nullable<decimal> idSubSick { get; set; }
        public Nullable<decimal> Sub { get; set; }
        public string FNamesick { get; set; }
        public string LNamesick { get; set; }
        public string sex { get; set; }
        public string meliCode { get; set; }
        public string Birthday { get; set; }
        public string Birthday_ostan { get; set; }
        public string Birthday_city { get; set; }
        public string sokonat_ostan { get; set; }
        public string sokonat_city { get; set; }
        public string city { get; set; }
        public string addr { get; set; }
        public string Tel { get; set; }
        public string TelQuick { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> ID_insur { get; set; }
        public string date_create { get; set; }
        public string code_bimeh { get; set; }
        public string Code_BimehSecond { get; set; }
        public string identifier { get; set; }
        public Nullable<decimal> id_nesbat { get; set; }
        public Nullable<decimal> id_niro { get; set; }
        public Nullable<decimal> id_Status { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string name_user { get; set; }
        public string date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<int> CenterID { get; set; }
        public string illnessS { get; set; }
        public string Father { get; set; }
        public string idSick_Prior { get; set; }
        public string ID1 { get; set; }
        public Nullable<decimal> kind_Bimeh { get; set; }
        public Nullable<bool> Checked { get; set; }
        public string age { get; set; }
        public string job_location { get; set; }
        public Nullable<int> id_ghesmat { get; set; }
        public Nullable<decimal> id_insur_mokamel { get; set; }
        public string date_etebar { get; set; }
        public Nullable<decimal> section { get; set; }
        public string date_special_sick { get; set; }
        public string SickArchive { get; set; }
        public string job { get; set; }
        public string education { get; set; }
        public Nullable<byte> marrried_single { get; set; }
        public Nullable<double> weigh { get; set; }
        public Nullable<double> size { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<byte> RH { get; set; }
        public Nullable<byte> kind_marrried { get; set; }
        public Nullable<decimal> id_user_delete { get; set; }
        public string comment { get; set; }
        public Nullable<byte> Flag_Card { get; set; }
        public Nullable<int> id_identifier { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<AccountCustomer> AccountCustomers { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<AccountCustomerDetail> AccountCustomerDetails { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<FamilyDoctorMaster> FamilyDoctorMasters { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<Hazineh2> Hazineh2 { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<HISFamilyDocResponseDetail> HISFamilyDocResponseDetails { get; set; }
        //public virtual HISFamilyDocResponseMaster HISFamilyDocResponseMaster { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<IllnessFileMaster> IllnessFileMasters { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<IllnessFileRequest> IllnessFileRequests { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<IllnessHistory_Compliant> IllnessHistory_Compliant { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<IllnessHistory_Detail1> IllnessHistory_Detail1 { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<IllnessHistory_Detail2> IllnessHistory_Detail2 { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<IllnessHistory_Detail3> IllnessHistory_Detail3 { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<IllnessHistory_Drug_Interaction> IllnessHistory_Drug_Interaction { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<IllnessHistory_Drug_Use> IllnessHistory_Drug_Use { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<IllnessHistory_Family> IllnessHistory_Family { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<IllnessHistory_Past> IllnessHistory_Past { get; set; }
        //public virtual IllnessHistory_Surgery_Hospital IllnessHistory_Surgery_Hospital { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<infosick_detail> infosick_detail { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<NobatDetail5> NobatDetail5 { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<Paziresh2> Paziresh2 { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<Paziresh3> Paziresh3 { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<Paziresh4> Paziresh4 { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<Paziresh8> Paziresh8 { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<Rulesaghf_baharan_master> Rulesaghf_baharan_master { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<RuleSaghfFardi1> RuleSaghfFardi1 { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<RuleSaghfFardi2> RuleSaghfFardi2 { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<RuleSaghfFardi4> RuleSaghfFardi4 { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<RuleSaghfFardi5> RuleSaghfFardi5 { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<visiting> visitings { get; set; }
    }
}
