//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoService5_Section
    {
        public decimal ID { get; set; }
        public Nullable<decimal> id_service { get; set; }
        public Nullable<decimal> id_section { get; set; }
        public Nullable<decimal> Id_user { get; set; }
        public string date_edit { get; set; }
        public string time_edit { get; set; }
    
        public virtual InfoSection5 InfoSection5 { get; set; }
        public virtual InfoService5 InfoService5 { get; set; }
        public virtual Infouser Infouser { get; set; }
    }
}
