//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class infoniro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public infoniro()
        {
            this.Calculate_Before_free_insur = new HashSet<Calculate_Before_free_insur>();
            this.Paziresh8 = new HashSet<Paziresh8>();
            this.PersonalRahs = new HashSet<PersonalRah>();
            this.RuleSaghfgrp_Niro = new HashSet<RuleSaghfgrp_Niro>();
        }
    
        public decimal idniro { get; set; }
        public int CenterID { get; set; }
        public Nullable<decimal> idsubniro { get; set; }
        public string NameNiro { get; set; }
        public Nullable<decimal> idindex { get; set; }
        public string NodePtr { get; set; }
        public Nullable<bool> Checked { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<bool> active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calculate_Before_free_insur> Calculate_Before_free_insur { get; set; }
        public virtual infoCenteral infoCenteral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paziresh8> Paziresh8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalRah> PersonalRahs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleSaghfgrp_Niro> RuleSaghfgrp_Niro { get; set; }
    }
}
