//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoRadio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InfoRadio()
        {
            this.FamilyDoctorDetail_Radio = new HashSet<FamilyDoctorDetail_Radio>();
            this.infoProtocol_Mokamel_Detail4 = new HashSet<infoProtocol_Mokamel_Detail4>();
            this.InfoProtocolDetail_Center4 = new HashSet<InfoProtocolDetail_Center4>();
            this.Paziresh4_detail1 = new HashSet<Paziresh4_detail1>();
            this.Paziresh4 = new HashSet<Paziresh4>();
            this.ProtocolRadios = new HashSet<ProtocolRadio>();
            this.Queue_paz = new HashSet<Queue_paz>();
            this.RadioGroups = new HashSet<RadioGroup>();
            this.RadioGroups1 = new HashSet<RadioGroup>();
            this.RadioMabs = new HashSet<RadioMab>();
            this.RadioMaterialMasrafis = new HashSet<RadioMaterialMasrafi>();
            this.Ready4 = new HashSet<Ready4>();
            this.RuleSaghfFardi_ServiceDetail4 = new HashSet<RuleSaghfFardi_ServiceDetail4>();
        }
    
        public int Code { get; set; }
        public int RowID { get; set; }
        public int CodeManual { get; set; }
        public Nullable<int> idsub { get; set; }
        public string FarsiName { get; set; }
        public string LatinName { get; set; }
        public string NameEkhtesar { get; set; }
        public Nullable<byte> IsGroup { get; set; }
        public Nullable<int> impossibleSelected { get; set; }
        public string CodeInterNational { get; set; }
        public string NodePtr { get; set; }
        public Nullable<decimal> ID_User { get; set; }
        public string date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<bool> Checked { get; set; }
        public Nullable<int> KindID { get; set; }
        public Nullable<byte> Time_do { get; set; }
        public Nullable<int> CenterID { get; set; }
        public Nullable<byte> Kind { get; set; }
        public string servicegroup { get; set; }
        public Nullable<int> mis_code { get; set; }
        public Nullable<int> ID_KarServiceGrp { get; set; }
        public string TaminIDTypePara { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FamilyDoctorDetail_Radio> FamilyDoctorDetail_Radio { get; set; }
        public virtual infoCenteral infoCenteral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoProtocol_Mokamel_Detail4> infoProtocol_Mokamel_Detail4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoProtocolDetail_Center4> InfoProtocolDetail_Center4 { get; set; }
        public virtual Infouser Infouser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paziresh4_detail1> Paziresh4_detail1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paziresh4> Paziresh4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProtocolRadio> ProtocolRadios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Queue_paz> Queue_paz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RadioGroup> RadioGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RadioGroup> RadioGroups1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RadioMab> RadioMabs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RadioMaterialMasrafi> RadioMaterialMasrafis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ready4> Ready4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleSaghfFardi_ServiceDetail4> RuleSaghfFardi_ServiceDetail4 { get; set; }
    }
}
