//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoProtocolDetail8
    {
        public decimal ID { get; set; }
        public Nullable<decimal> RuleID_Master { get; set; }
        public Nullable<int> id_Service { get; set; }
        public Nullable<decimal> id_takhasos { get; set; }
        public Nullable<decimal> Per_Org { get; set; }
        public Nullable<decimal> Per_illness { get; set; }
        public Nullable<decimal> Mab_Service { get; set; }
        public Nullable<decimal> Mab_K { get; set; }
        public Nullable<decimal> Count_K { get; set; }
        public Nullable<decimal> Mab_Additional { get; set; }
        public Nullable<bool> SendToInsur { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string date_edit { get; set; }
        public string time_edit { get; set; }
    
        public virtual InfoProtocolMaster8 InfoProtocolMaster8 { get; set; }
        public virtual infoService8 infoService8 { get; set; }
        public virtual infotakhasos8 infotakhasos8 { get; set; }
        public virtual Infouser Infouser { get; set; }
    }
}
