//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoSoftware
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InfoSoftware()
        {
            this.AuthUsers = new HashSet<AuthUser>();
            this.BasicUsers = new HashSet<BasicUser>();
            this.Calculate_Before_free_insur = new HashSet<Calculate_Before_free_insur>();
            this.FamilyDoctorCenterSettings = new HashSet<FamilyDoctorCenterSetting>();
            this.InfoNobatComments = new HashSet<InfoNobatComment>();
            this.InfoSendDiskSettings = new HashSet<InfoSendDiskSetting>();
            this.Payment_Software = new HashSet<Payment_Software>();
            this.Queue_paz = new HashSet<Queue_paz>();
            this.Queue_User = new HashSet<Queue_User>();
            this.Service_Group_Master = new HashSet<Service_Group_Master>();
            this.Service_just_one = new HashSet<Service_just_one>();
            this.SMSMsgs = new HashSet<SMSMsg>();
        }
    
        public int ID { get; set; }
        public string descript { get; set; }
        public System.DateTime date_edit { get; set; }
        public Nullable<bool> @checked { get; set; }
        public Nullable<int> code_group { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuthUser> AuthUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasicUser> BasicUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calculate_Before_free_insur> Calculate_Before_free_insur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FamilyDoctorCenterSetting> FamilyDoctorCenterSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoNobatComment> InfoNobatComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoSendDiskSetting> InfoSendDiskSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment_Software> Payment_Software { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Queue_paz> Queue_paz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Queue_User> Queue_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_Group_Master> Service_Group_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_just_one> Service_just_one { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMSMsg> SMSMsgs { get; set; }
    }
}
