//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoSection5
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InfoSection5()
        {
            this.CalenderDetail_Section5 = new HashSet<CalenderDetail_Section5>();
            this.infoDoctor_Detail5 = new HashSet<infoDoctor_Detail5>();
            this.InfoSection51 = new HashSet<InfoSection5>();
            this.InfoService5_Section = new HashSet<InfoService5_Section>();
            this.Paziresh_nos_fizio = new HashSet<Paziresh_nos_fizio>();
            this.Paziresh5 = new HashSet<Paziresh5>();
        }
    
        public decimal Code { get; set; }
        public string CodeManual { get; set; }
        public Nullable<decimal> idsub { get; set; }
        public Nullable<int> CenterID { get; set; }
        public string NameSection { get; set; }
        public Nullable<bool> @checked { get; set; }
        public Nullable<byte> fix { get; set; }
        public Nullable<decimal> Id_user { get; set; }
        public string date_edit { get; set; }
        public string time_edit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalenderDetail_Section5> CalenderDetail_Section5 { get; set; }
        public virtual infoCenteral infoCenteral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoDoctor_Detail5> infoDoctor_Detail5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoSection5> InfoSection51 { get; set; }
        public virtual InfoSection5 InfoSection52 { get; set; }
        public virtual Infouser Infouser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoService5_Section> InfoService5_Section { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paziresh_nos_fizio> Paziresh_nos_fizio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paziresh5> Paziresh5 { get; set; }
    }
}
