//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class infoProtocol_Mokamel_Master5
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public infoProtocol_Mokamel_Master5()
        {
            this.infoProtocol_Mokamel_Detail_insur5 = new HashSet<infoProtocol_Mokamel_Detail_insur5>();
            this.infoProtocol_Mokamel_Detail5 = new HashSet<infoProtocol_Mokamel_Detail5>();
        }
    
        public decimal RuleID { get; set; }
        public Nullable<decimal> id_insur_Mokamel { get; set; }
        public Nullable<int> CenterID { get; set; }
        public string D_Run { get; set; }
        public string D_Expire { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string date_Edit { get; set; }
        public string Time_Edit { get; set; }
    
        public virtual infoCenteral infoCenteral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoProtocol_Mokamel_Detail_insur5> infoProtocol_Mokamel_Detail_insur5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoProtocol_Mokamel_Detail5> infoProtocol_Mokamel_Detail5 { get; set; }
        public virtual insur insur { get; set; }
    }
}
