//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoTypespecial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InfoTypespecial()
        {
            this.infoProtocol_Mokamel_Detail1 = new HashSet<infoProtocol_Mokamel_Detail1>();
            this.infoProtocol_Mokamel_Detail11 = new HashSet<infoProtocol_Mokamel_Detail1>();
            this.infoprotocolMaterialMasters = new HashSet<infoprotocolMaterialMaster>();
        }
    
        public decimal IDTypespecial { get; set; }
        public string NameTypespecial { get; set; }
        public Nullable<bool> fix { get; set; }
        public Nullable<decimal> idindex { get; set; }
        public string NodePtr { get; set; }
        public Nullable<bool> Checked { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string name_user { get; set; }
        public string date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<int> CenterID { get; set; }
        public Nullable<int> mis_code { get; set; }
    
        public virtual infoCenteral infoCenteral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoProtocol_Mokamel_Detail1> infoProtocol_Mokamel_Detail1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoProtocol_Mokamel_Detail1> infoProtocol_Mokamel_Detail11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoprotocolMaterialMaster> infoprotocolMaterialMasters { get; set; }
    }
}
