//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class infoCenteral
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public infoCenteral()
        {
            this.abates = new HashSet<abate>();
            this.absent_persent = new HashSet<absent_persent>();
            this.AccountCustomerMaxes = new HashSet<AccountCustomerMax>();
            this.aghsat_master = new HashSet<aghsat_master>();
            this.amvals = new HashSet<amval>();
            this.anbarmaterials = new HashSet<anbarmaterial>();
            this.Antibiotics = new HashSet<Antibiotic>();
            this.AuthUsers = new HashSet<AuthUser>();
            this.BackIllnesses = new HashSet<BackIllness>();
            this.BasicinfoKinds = new HashSet<BasicinfoKind>();
            this.BasicUsers = new HashSet<BasicUser>();
            this.Beyanehs = new HashSet<Beyaneh>();
            this.CalenderMaster1 = new HashSet<CalenderMaster1>();
            this.CalenderMaster5 = new HashSet<CalenderMaster5>();
            this.cause_takhfif = new HashSet<cause_takhfif>();
            this.CenterSoftwarePeyGiris = new HashSet<CenterSoftwarePeyGiri>();
            this.define_anbar = new HashSet<define_anbar>();
            this.DefineAllIllnesses = new HashSet<DefineAllIllness>();
            this.defultsofts = new HashSet<defultsoft>();
            this.detailLabs = new HashSet<detailLab>();
            this.DeviceLab_Log = new HashSet<DeviceLab_Log>();
            this.doctorDetails = new HashSet<doctorDetail>();
            this.DoLabs = new HashSet<DoLab>();
            this.Drugcost_Protocol = new HashSet<Drugcost_Protocol>();
            this.FamilyDoctorMasters = new HashSet<FamilyDoctorMaster>();
            this.Hazinehs = new HashSet<Hazineh>();
            this.Hazineh2 = new HashSet<Hazineh2>();
            this.HazinehLabs = new HashSet<HazinehLab>();
            this.Holidays = new HashSet<Holiday>();
            this.IllnessFileMasters = new HashSet<IllnessFileMaster>();
            this.IllnessFileRequests = new HashSet<IllnessFileRequest>();
            this.Infoaddabates = new HashSet<Infoaddabate>();
            this.Infoanbars = new HashSet<Infoanbar>();
            this.InfoBuyers = new HashSet<InfoBuyer>();
            this.InfoCashiers = new HashSet<InfoCashier>();
            this.Infocauses = new HashSet<Infocause>();
            this.InfoCauseDaryafts = new HashSet<InfoCauseDaryaft>();
            this.infocausedetails = new HashSet<infocausedetail>();
            this.InfoCausePardakhts = new HashSet<InfoCausePardakht>();
            this.block_illness = new HashSet<block_illness>();
            this.cause_delete = new HashSet<cause_delete>();
            this.ChartTests = new HashSet<ChartTest>();
            this.Configs = new HashSet<Config>();
            this.Infochops = new HashSet<Infochop>();
            this.infoDaroHasasiatzas = new HashSet<infoDaroHasasiatza>();
            this.infoDegrees = new HashSet<infoDegree>();
            this.Infodentists = new HashSet<Infodentist>();
            this.infoDeviceLab_Center = new HashSet<infoDeviceLab_Center>();
            this.infodoes = new HashSet<infodo>();
            this.infoDoctor_Detail5 = new HashSet<infoDoctor_Detail5>();
            this.InfoEbtals = new HashSet<InfoEbtal>();
            this.infoeducations = new HashSet<infoeducation>();
            this.infoinsur_not_do = new HashSet<infoinsur_not_do>();
            this.infokarShenasRadios = new HashSet<infokarShenasRadio>();
            this.InfoLabs = new HashSet<InfoLab>();
            this.InfoMaterials = new HashSet<InfoMaterial>();
            this.infonahads = new HashSet<infonahad>();
            this.infonesbats = new HashSet<infonesbat>();
            this.infoniroes = new HashSet<infoniro>();
            this.infoozvs = new HashSet<infoozv>();
            this.InfoProtocols = new HashSet<InfoProtocol>();
            this.infoProtocol_K5 = new HashSet<infoProtocol_K5>();
            this.infoProtocol_Mokamel_Master1 = new HashSet<infoProtocol_Mokamel_Master1>();
            this.infoProtocol_Mokamel_Master2 = new HashSet<infoProtocol_Mokamel_Master2>();
            this.infoProtocol_Mokamel_Master4 = new HashSet<infoProtocol_Mokamel_Master4>();
            this.infoProtocol_Mokamel_Master5 = new HashSet<infoProtocol_Mokamel_Master5>();
            this.InfoProtocolDetail_Center1 = new HashSet<InfoProtocolDetail_Center1>();
            this.InfoProtocolDetail_Center2 = new HashSet<InfoProtocolDetail_Center2>();
            this.InfoProtocolDetail_Center4 = new HashSet<InfoProtocolDetail_Center4>();
            this.InfoProtocolDetail_Center5 = new HashSet<InfoProtocolDetail_Center5>();
            this.InfoProtocolDetail1_file = new HashSet<InfoProtocolDetail1_file>();
            this.InfoProtocolDetail2_file = new HashSet<InfoProtocolDetail2_file>();
            this.InfoProtocolDetail4_file = new HashSet<InfoProtocolDetail4_file>();
            this.InfoProtocolDetail5_file = new HashSet<InfoProtocolDetail5_file>();
            this.InfoProtocolMaster2 = new HashSet<InfoProtocolMaster2>();
            this.InfoProtocolMaster4 = new HashSet<InfoProtocolMaster4>();
            this.InfoProtocolMaster5 = new HashSet<InfoProtocolMaster5>();
            this.InfoProtocolMaster8 = new HashSet<InfoProtocolMaster8>();
            this.Infoquestions = new HashSet<Infoquestion>();
            this.InfoRadios = new HashSet<InfoRadio>();
            this.infoSections = new HashSet<infoSection>();
            this.InfoSection5 = new HashSet<InfoSection5>();
            this.infoServices = new HashSet<infoService>();
            this.infoservice_not_do = new HashSet<infoservice_not_do>();
            this.infoService8 = new HashSet<infoService8>();
            this.InfoShifts = new HashSet<InfoShift>();
            this.infosick_detail = new HashSet<infosick_detail>();
            this.Infospecials = new HashSet<Infospecial>();
            this.InfoStatus = new HashSet<InfoStatu>();
            this.InfoSystems = new HashSet<InfoSystem>();
            this.infotakhasos5 = new HashSet<infotakhasos5>();
            this.infotakhasos8 = new HashSet<infotakhasos8>();
            this.InfoTest_Detail = new HashSet<InfoTest_Detail>();
            this.InfoTest_LBLPrintMaster = new HashSet<InfoTest_LBLPrintMaster>();
            this.Infoteeth = new HashSet<Infotooth>();
            this.InfotoothSpoils = new HashSet<InfotoothSpoil>();
            this.InfoTypeNobats = new HashSet<InfoTypeNobat>();
            this.InfoTypespecials = new HashSet<InfoTypespecial>();
            this.infounits = new HashSet<infounit>();
            this.infounitLabs = new HashSet<infounitLab>();
            this.infovendors = new HashSet<infovendor>();
            this.insurs = new HashSet<insur>();
            this.InsurServices = new HashSet<InsurService>();
            this.kosordentists = new HashSet<kosordentist>();
            this.kosordoctor5 = new HashSet<kosordoctor5>();
            this.Listkars = new HashSet<Listkar>();
            this.Logins = new HashSet<Login>();
            this.Makharejs = new HashSet<Makharej>();
            this.managerlabs = new HashSet<managerlab>();
            this.Motalebats = new HashSet<Motalebat>();
            this.nobat_reserv_master = new HashSet<nobat_reserv_master>();
            this.NobatMaster1 = new HashSet<NobatMaster1>();
            this.NobatMaster5 = new HashSet<NobatMaster5>();
            this.OptionPato_Cyto = new HashSet<OptionPato_Cyto>();
            this.OptionPicManages = new HashSet<OptionPicManage>();
            this.OptionRadios = new HashSet<OptionRadio>();
            this.OptionRadios1 = new HashSet<OptionRadio>();
            this.options = new HashSet<option>();
            this.Par_Dar = new HashSet<Par_Dar>();
            this.Payment_Software = new HashSet<Payment_Software>();
            this.Paziresh_nos_fizio = new HashSet<Paziresh_nos_fizio>();
            this.Paziresh2 = new HashSet<Paziresh2>();
            this.Paziresh3 = new HashSet<Paziresh3>();
            this.Paziresh4 = new HashSet<Paziresh4>();
            this.Paziresh5 = new HashSet<Paziresh5>();
            this.Paziresh7 = new HashSet<Paziresh7>();
            this.Paziresh8 = new HashSet<Paziresh8>();
            this.Pictures = new HashSet<Picture>();
            this.Protocols = new HashSet<Protocol>();
            this.Questions = new HashSet<Question>();
            this.Questions1 = new HashSet<Question>();
            this.Queue_paz = new HashSet<Queue_paz>();
            this.Queue_User = new HashSet<Queue_User>();
            this.QueueBakhshes = new HashSet<QueueBakhsh>();
            this.Ready4 = new HashSet<Ready4>();
            this.readytests = new HashSet<readytest>();
            this.Recieve_Hoghogh = new HashSet<Recieve_Hoghogh>();
            this.RecNo_New = new HashSet<RecNo_New>();
            this.result_formol = new HashSet<result_formol>();
            this.RulePaymentDetails = new HashSet<RulePaymentDetail>();
            this.Rulesaghf_baharan_master = new HashSet<Rulesaghf_baharan_master>();
            this.RuleSaghfFardi1 = new HashSet<RuleSaghfFardi1>();
            this.RuleSaghfFardi2 = new HashSet<RuleSaghfFardi2>();
            this.RuleSaghfFardi4 = new HashSet<RuleSaghfFardi4>();
            this.RuleSaghfFardi5 = new HashSet<RuleSaghfFardi5>();
            this.RuleSalaryMaster1_1175 = new HashSet<RuleSalaryMaster1_1175>();
            this.RuleSalaryMaster1 = new HashSet<RuleSalaryMaster1>();
            this.RuleSalaryMaster5_1056 = new HashSet<RuleSalaryMaster5_1056>();
            this.RuleSalaryMaster5 = new HashSet<RuleSalaryMaster5>();
            this.RuleSalaryMaster564 = new HashSet<RuleSalaryMaster564>();
            this.Service_Group_Master = new HashSet<Service_Group_Master>();
            this.takhfif_Detail_Center = new HashSet<takhfif_Detail_Center>();
            this.takhfif2 = new HashSet<takhfif2>();
            this.tarhdarmen = new HashSet<tarhdarman>();
            this.tashkhis = new HashSet<tashkhi>();
            this.tels = new HashSet<tel>();
            this.TestDetail1 = new HashSet<TestDetail1>();
            this.TestDetail2 = new HashSet<TestDetail2>();
            this.TestGroups = new HashSet<TestGroup>();
            this.upgrades = new HashSet<upgrade>();
            this.UserDetails = new HashSet<UserDetail>();
            this.visitings = new HashSet<visiting>();
            this.yaraneh_Detail_Center = new HashSet<yaraneh_Detail_Center>();
            this.yaraneh2 = new HashSet<yaraneh2>();
        }
    
        public int Code { get; set; }
        public string NameCenteral { get; set; }
        public string Tel { get; set; }
        public string Addr { get; set; }
        public Nullable<int> FromIP1 { get; set; }
        public Nullable<int> FromIP2 { get; set; }
        public Nullable<int> FromIP3 { get; set; }
        public Nullable<int> FromIP4 { get; set; }
        public Nullable<int> ToIP1 { get; set; }
        public Nullable<int> ToIP2 { get; set; }
        public Nullable<int> ToIP3 { get; set; }
        public Nullable<int> ToIP4 { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<bool> Checked { get; set; }
        public string ResultTimeLab { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<abate> abates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<absent_persent> absent_persent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountCustomerMax> AccountCustomerMaxes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aghsat_master> aghsat_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<amval> amvals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<anbarmaterial> anbarmaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Antibiotic> Antibiotics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuthUser> AuthUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BackIllness> BackIllnesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasicinfoKind> BasicinfoKinds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasicUser> BasicUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Beyaneh> Beyanehs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalenderMaster1> CalenderMaster1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalenderMaster5> CalenderMaster5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cause_takhfif> cause_takhfif { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CenterSoftwarePeyGiri> CenterSoftwarePeyGiris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<define_anbar> define_anbar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefineAllIllness> DefineAllIllnesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<defultsoft> defultsofts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detailLab> detailLabs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceLab_Log> DeviceLab_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doctorDetail> doctorDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoLab> DoLabs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Drugcost_Protocol> Drugcost_Protocol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FamilyDoctorMaster> FamilyDoctorMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hazineh> Hazinehs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hazineh2> Hazineh2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HazinehLab> HazinehLabs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Holiday> Holidays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IllnessFileMaster> IllnessFileMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IllnessFileRequest> IllnessFileRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Infoaddabate> Infoaddabates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Infoanbar> Infoanbars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoBuyer> InfoBuyers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoCashier> InfoCashiers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Infocause> Infocauses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoCauseDaryaft> InfoCauseDaryafts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infocausedetail> infocausedetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoCausePardakht> InfoCausePardakhts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<block_illness> block_illness { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cause_delete> cause_delete { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChartTest> ChartTests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Config> Configs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Infochop> Infochops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoDaroHasasiatza> infoDaroHasasiatzas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoDegree> infoDegrees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Infodentist> Infodentists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoDeviceLab_Center> infoDeviceLab_Center { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infodo> infodoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoDoctor_Detail5> infoDoctor_Detail5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoEbtal> InfoEbtals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoeducation> infoeducations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoinsur_not_do> infoinsur_not_do { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infokarShenasRadio> infokarShenasRadios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoLab> InfoLabs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoMaterial> InfoMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infonahad> infonahads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infonesbat> infonesbats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoniro> infoniroes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoozv> infoozvs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoProtocol> InfoProtocols { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoProtocol_K5> infoProtocol_K5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoProtocol_Mokamel_Master1> infoProtocol_Mokamel_Master1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoProtocol_Mokamel_Master2> infoProtocol_Mokamel_Master2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoProtocol_Mokamel_Master4> infoProtocol_Mokamel_Master4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoProtocol_Mokamel_Master5> infoProtocol_Mokamel_Master5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoProtocolDetail_Center1> InfoProtocolDetail_Center1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoProtocolDetail_Center2> InfoProtocolDetail_Center2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoProtocolDetail_Center4> InfoProtocolDetail_Center4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoProtocolDetail_Center5> InfoProtocolDetail_Center5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoProtocolDetail1_file> InfoProtocolDetail1_file { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoProtocolDetail2_file> InfoProtocolDetail2_file { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoProtocolDetail4_file> InfoProtocolDetail4_file { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoProtocolDetail5_file> InfoProtocolDetail5_file { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoProtocolMaster2> InfoProtocolMaster2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoProtocolMaster4> InfoProtocolMaster4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoProtocolMaster5> InfoProtocolMaster5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoProtocolMaster8> InfoProtocolMaster8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Infoquestion> Infoquestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoRadio> InfoRadios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoSection> infoSections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoSection5> InfoSection5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoService> infoServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoservice_not_do> infoservice_not_do { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoService8> infoService8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoShift> InfoShifts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infosick_detail> infosick_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Infospecial> Infospecials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoStatu> InfoStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoSystem> InfoSystems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infotakhasos5> infotakhasos5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infotakhasos8> infotakhasos8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoTest_Detail> InfoTest_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoTest_LBLPrintMaster> InfoTest_LBLPrintMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Infotooth> Infoteeth { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfotoothSpoil> InfotoothSpoils { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoTypeNobat> InfoTypeNobats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoTypespecial> InfoTypespecials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infounit> infounits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infounitLab> infounitLabs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infovendor> infovendors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<insur> insurs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsurService> InsurServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kosordentist> kosordentists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kosordoctor5> kosordoctor5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Listkar> Listkars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Login> Logins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Makharej> Makharejs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<managerlab> managerlabs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Motalebat> Motalebats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nobat_reserv_master> nobat_reserv_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NobatMaster1> NobatMaster1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NobatMaster5> NobatMaster5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OptionPato_Cyto> OptionPato_Cyto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OptionPicManage> OptionPicManages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OptionRadio> OptionRadios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OptionRadio> OptionRadios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<option> options { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Par_Dar> Par_Dar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment_Software> Payment_Software { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paziresh_nos_fizio> Paziresh_nos_fizio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paziresh2> Paziresh2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paziresh3> Paziresh3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paziresh4> Paziresh4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paziresh5> Paziresh5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paziresh7> Paziresh7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paziresh8> Paziresh8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Picture> Pictures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Protocol> Protocols { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question> Questions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question> Questions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Queue_paz> Queue_paz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Queue_User> Queue_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QueueBakhsh> QueueBakhshes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ready4> Ready4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<readytest> readytests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recieve_Hoghogh> Recieve_Hoghogh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecNo_New> RecNo_New { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<result_formol> result_formol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RulePaymentDetail> RulePaymentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rulesaghf_baharan_master> Rulesaghf_baharan_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleSaghfFardi1> RuleSaghfFardi1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleSaghfFardi2> RuleSaghfFardi2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleSaghfFardi4> RuleSaghfFardi4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleSaghfFardi5> RuleSaghfFardi5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleSalaryMaster1_1175> RuleSalaryMaster1_1175 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleSalaryMaster1> RuleSalaryMaster1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleSalaryMaster5_1056> RuleSalaryMaster5_1056 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleSalaryMaster5> RuleSalaryMaster5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleSalaryMaster564> RuleSalaryMaster564 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_Group_Master> Service_Group_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<takhfif_Detail_Center> takhfif_Detail_Center { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<takhfif2> takhfif2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tarhdarman> tarhdarmen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tashkhi> tashkhis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tel> tels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestDetail1> TestDetail1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestDetail2> TestDetail2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestGroup> TestGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<upgrade> upgrades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserDetail> UserDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visiting> visitings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<yaraneh_Detail_Center> yaraneh_Detail_Center { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<yaraneh2> yaraneh2 { get; set; }
    }
}
