//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoService5_SendToInsurDetail
    {
        public decimal ID { get; set; }
        public Nullable<decimal> ID_InfoService5_SendToInsurMaster { get; set; }
        public Nullable<decimal> id_Service { get; set; }
        public string code_send { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string Date_Edit { get; set; }
        public string Time_Edit { get; set; }
    
        public virtual InfoService5_SendToInsurMaster InfoService5_SendToInsurMaster { get; set; }
        public virtual Infouser Infouser { get; set; }
    }
}
