//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class infoService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public infoService()
        {
            //this.CalenderDetail_Section1 = new HashSet<CalenderDetail_Section1>();
            //this.Infodentist_DetailSection = new HashSet<Infodentist_DetailSection>();
            //this.infoProtocol_Mokamel_Detail1 = new HashSet<infoProtocol_Mokamel_Detail1>();
            //this.infoprotocolMaterialMasters = new HashSet<infoprotocolMaterialMaster>();
            //this.infoService1_NotCalculated_Salary = new HashSet<infoService1_NotCalculated_Salary>();
            //this.infovisit1 = new HashSet<infovisit1>();
            //this.NobatDetail1 = new HashSet<NobatDetail1>();
            //this.Rule_serviceS_detail_dependent = new HashSet<Rule_serviceS_detail_dependent>();
            //this.Rule_serviceS_detail = new HashSet<Rule_serviceS_detail>();
            //this.RuleSaghfFardi_ServiceDetail1 = new HashSet<RuleSaghfFardi_ServiceDetail1>();
            //this.RuleSalaryDetail_Service1_1175 = new HashSet<RuleSalaryDetail_Service1_1175>();
            //this.RuleSalaryDetail_Service1 = new HashSet<RuleSalaryDetail_Service1>();
            //this.RuleSalaryDetail_Service564 = new HashSet<RuleSalaryDetail_Service564>();
            //this.RuleSalaryDetail600 = new HashSet<RuleSalaryDetail600>();
            //this.visitings = new HashSet<visiting>();
        }
    
        public decimal IDService { get; set; }
        public int CenterID { get; set; }
        public Nullable<decimal> IDSub { get; set; }
        public string NameService { get; set; }
        public string TimeService { get; set; }
        public Nullable<bool> fix { get; set; }
        public Nullable<decimal> idindex { get; set; }
        public string NodePtr { get; set; }
        public Nullable<bool> Checked { get; set; }
        public Nullable<int> Choice_dental { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public string CodeSend { get; set; }
        public string codesend2 { get; set; }
        public string nameservice_latin { get; set; }
        public Nullable<int> id_TypeService { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> InternalServiceInCenter { get; set; }
        public string txtpayamak { get; set; }
        public Nullable<byte> flag_tarmim { get; set; }
        public Nullable<int> mis_code { get; set; }
        public Nullable<int> ID_KarServiceGrp { get; set; }
        public string codesend105 { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<CalenderDetail_Section1> CalenderDetail_Section1 { get; set; }
        //public virtual infoCenteral infoCenteral { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<Infodentist_DetailSection> Infodentist_DetailSection { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<infoProtocol_Mokamel_Detail1> infoProtocol_Mokamel_Detail1 { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<infoprotocolMaterialMaster> infoprotocolMaterialMasters { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<infoService1_NotCalculated_Salary> infoService1_NotCalculated_Salary { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<infovisit1> infovisit1 { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<NobatDetail1> NobatDetail1 { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<Rule_serviceS_detail_dependent> Rule_serviceS_detail_dependent { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<Rule_serviceS_detail> Rule_serviceS_detail { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<RuleSaghfFardi_ServiceDetail1> RuleSaghfFardi_ServiceDetail1 { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<RuleSalaryDetail_Service1_1175> RuleSalaryDetail_Service1_1175 { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<RuleSalaryDetail_Service1> RuleSalaryDetail_Service1 { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<RuleSalaryDetail_Service564> RuleSalaryDetail_Service564 { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<RuleSalaryDetail600> RuleSalaryDetail600 { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<visiting> visitings { get; set; }
    }
}
