//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class infoDeviceLab_Center
    {
        public decimal ID { get; set; }
        public Nullable<decimal> ID_infoDeviceLab { get; set; }
        public int CenterID { get; set; }
    
        public virtual infoCenteral infoCenteral { get; set; }
        public virtual infoDeviceLab infoDeviceLab { get; set; }
    }
}
