//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class infoDeviceLab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public infoDeviceLab()
        {
            this.infoDeviceLab_Center = new HashSet<infoDeviceLab_Center>();
            this.infoDeviceLab_Coding = new HashSet<infoDeviceLab_Coding>();
        }
    
        public decimal ID { get; set; }
        public string NameDevice { get; set; }
        public decimal id_Section { get; set; }
        public string Port { get; set; }
        public Nullable<int> BaudRate { get; set; }
        public Nullable<int> DataBit { get; set; }
        public Nullable<double> StopBits { get; set; }
        public Nullable<byte> Parity { get; set; }
        public Nullable<byte> FlowControl { get; set; }
        public decimal id_user { get; set; }
        public string date_Edit { get; set; }
        public string Time_Edit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoDeviceLab_Center> infoDeviceLab_Center { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoDeviceLab_Coding> infoDeviceLab_Coding { get; set; }
        public virtual InfoTest InfoTest { get; set; }
        public virtual Infouser Infouser { get; set; }
    }
}
