//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class infoService5_kal
    {
        public int Code { get; set; }
        public string CodeManual { get; set; }
        public string NameGroup { get; set; }
        public string NameService { get; set; }
        public string Nah1 { get; set; }
        public string Nah2 { get; set; }
        public string Nah2_Latin { get; set; }
        public Nullable<double> Mab_Service { get; set; }
        public Nullable<double> K_jarahi { get; set; }
        public Nullable<double> K_dakheli { get; set; }
        public Nullable<double> K_Bih { get; set; }
        public string Code_Kalif { get; set; }
    }
}
