//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class infoService8
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public infoService8()
        {
            this.InfoProtocolDetail8 = new HashSet<InfoProtocolDetail8>();
            this.Paziresh8_Detail1 = new HashSet<Paziresh8_Detail1>();
        }
    
        public int Code { get; set; }
        public Nullable<int> idsub { get; set; }
        public Nullable<int> CenterID { get; set; }
        public string Nameservice { get; set; }
        public string LatinName { get; set; }
        public string ekhtesari { get; set; }
        public Nullable<bool> @checked { get; set; }
        public Nullable<byte> fix { get; set; }
        public Nullable<bool> Use_K { get; set; }
        public Nullable<int> id_K { get; set; }
        public Nullable<decimal> Count_K { get; set; }
        public Nullable<int> ID_OZV { get; set; }
        public Nullable<decimal> Id_user { get; set; }
        public string date_edit { get; set; }
        public string time_edit { get; set; }
        public Nullable<int> id_TypeService { get; set; }
        public string CodeInterNational { get; set; }
        public Nullable<int> RowIDOrder { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> mis_code { get; set; }
        public Nullable<int> ID_KarServiceGrp { get; set; }
        public Nullable<byte> ISArzyabi { get; set; }
    
        public virtual Info_K8 Info_K8 { get; set; }
        public virtual infoCenteral infoCenteral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoProtocolDetail8> InfoProtocolDetail8 { get; set; }
        public virtual Infouser Infouser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paziresh8_Detail1> Paziresh8_Detail1 { get; set; }
    }
}
