//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoService5
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InfoService5()
        {
            this.FamilyDoctorDetail_Visit = new HashSet<FamilyDoctorDetail_Visit>();
            this.infoProtocol_Mokamel_Detail5 = new HashSet<infoProtocol_Mokamel_Detail5>();
            this.InfoProtocolDetail5 = new HashSet<InfoProtocolDetail5>();
            this.InfoService5_Section = new HashSet<InfoService5_Section>();
            this.infovisit5 = new HashSet<infovisit5>();
            this.NobatDetail5 = new HashSet<NobatDetail5>();
            this.Paziresh_nos_fizio = new HashSet<Paziresh_nos_fizio>();
            this.Paziresh5 = new HashSet<Paziresh5>();
            this.RuleSaghfFardi_ServiceDetail5 = new HashSet<RuleSaghfFardi_ServiceDetail5>();
            this.RuleSalaryDetail_Service5_1056 = new HashSet<RuleSalaryDetail_Service5_1056>();
            this.RuleSalaryDetail_Service5 = new HashSet<RuleSalaryDetail_Service5>();
        }
    
        public decimal Code { get; set; }
        public string CodeManual { get; set; }
        public Nullable<decimal> idsub { get; set; }
        public Nullable<int> CenterID { get; set; }
        public string Nameservice { get; set; }
        public string LatinName { get; set; }
        public string ekhtesari { get; set; }
        public Nullable<bool> @checked { get; set; }
        public Nullable<byte> fix { get; set; }
        public Nullable<bool> Use_K { get; set; }
        public Nullable<int> id_K { get; set; }
        public Nullable<decimal> Count_K { get; set; }
        public Nullable<decimal> Id_user { get; set; }
        public string date_edit { get; set; }
        public string time_edit { get; set; }
        public Nullable<int> id_TypeService { get; set; }
        public string CodeInterNational { get; set; }
        public Nullable<byte> Flag_leizer { get; set; }
        public Nullable<int> id_TypeService_fizio { get; set; }
        public Nullable<int> mis_code { get; set; }
        public Nullable<int> ID_KarServiceGrp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FamilyDoctorDetail_Visit> FamilyDoctorDetail_Visit { get; set; }
        public virtual info_K5 info_K5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoProtocol_Mokamel_Detail5> infoProtocol_Mokamel_Detail5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoProtocolDetail5> InfoProtocolDetail5 { get; set; }
        public virtual InfoService5 InfoService51 { get; set; }
        public virtual InfoService5 InfoService52 { get; set; }
        public virtual infoTypeService5 infoTypeService5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoService5_Section> InfoService5_Section { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infovisit5> infovisit5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NobatDetail5> NobatDetail5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paziresh_nos_fizio> Paziresh_nos_fizio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paziresh5> Paziresh5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleSaghfFardi_ServiceDetail5> RuleSaghfFardi_ServiceDetail5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleSalaryDetail_Service5_1056> RuleSalaryDetail_Service5_1056 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleSalaryDetail_Service5> RuleSalaryDetail_Service5 { get; set; }
    }
}
