//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoRadioPhraphy
    {
        public decimal idauto { get; set; }
        public decimal RowID { get; set; }
        public decimal Code { get; set; }
        public decimal VahedID { get; set; }
        public Nullable<decimal> IsGroup { get; set; }
        public Nullable<int> impossibleSelected { get; set; }
        public Nullable<decimal> IDSub { get; set; }
        public Nullable<decimal> CodeInterNational { get; set; }
        public string LatinName { get; set; }
        public string NameEkhtesar { get; set; }
        public string ContractName { get; set; }
        public Nullable<int> DoTestCenteral { get; set; }
        public Nullable<decimal> idindex { get; set; }
        public Nullable<decimal> ID_Unit { get; set; }
        public Nullable<decimal> Time_TestDo { get; set; }
        public Nullable<decimal> Mab_Dolati { get; set; }
        public Nullable<decimal> Mab_Khososi { get; set; }
        public Nullable<decimal> Mab_Other1 { get; set; }
        public Nullable<decimal> Mab_Other2 { get; set; }
        public string NodePtr { get; set; }
        public Nullable<int> CurrentRow { get; set; }
        public Nullable<decimal> ID_User { get; set; }
        public string date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<decimal> ID_UserDelete { get; set; }
        public string date_delete { get; set; }
        public string Time_delete { get; set; }
        public Nullable<int> Cancel_Flag { get; set; }
        public string Date_Expire { get; set; }
        public Nullable<bool> Checked { get; set; }
        public Nullable<int> Kind { get; set; }
        public Nullable<bool> is_PezPub { get; set; }
        public Nullable<bool> is_pezpri { get; set; }
        public Nullable<bool> is_mama { get; set; }
        public Nullable<bool> cheked { get; set; }
    }
}
