//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class infoDoctor5
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public infoDoctor5()
        {
            this.CalenderMaster5 = new HashSet<CalenderMaster5>();
            this.infoDoctor_Detail5 = new HashSet<infoDoctor_Detail5>();
            this.kosordoctor5 = new HashSet<kosordoctor5>();
        }
    
        public int Code { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Code_nezam { get; set; }
        public Nullable<decimal> id_takhasos { get; set; }
        public Nullable<decimal> code_karbari { get; set; }
        public Nullable<byte> Sex { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string date_edit { get; set; }
        public string time_edit { get; set; }
        public Nullable<bool> @checked { get; set; }
        public Nullable<bool> Active { get; set; }
        public string tel { get; set; }
        public Nullable<int> mis_code { get; set; }
        public string shomarehesab { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalenderMaster5> CalenderMaster5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoDoctor_Detail5> infoDoctor_Detail5 { get; set; }
        public virtual Infouser Infouser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kosordoctor5> kosordoctor5 { get; set; }
    }
}
