//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Infouser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Infouser()
        {
            this.AuthUsers = new HashSet<AuthUser>();
            this.BasicUsers = new HashSet<BasicUser>();
            this.Calculate_Before_free_insur = new HashSet<Calculate_Before_free_insur>();
            this.CalenderMaster1 = new HashSet<CalenderMaster1>();
            this.CalenderMaster5 = new HashSet<CalenderMaster5>();
            this.CenterSoftwarePeyGiris = new HashSet<CenterSoftwarePeyGiri>();
            this.CenterSoftwarePeyGiris1 = new HashSet<CenterSoftwarePeyGiri>();
            this.DeviceLab_Hitachi911Master = new HashSet<DeviceLab_Hitachi911Master>();
            this.DeviceLab_Log = new HashSet<DeviceLab_Log>();
            this.FamilyDoctorCenterSettings = new HashSet<FamilyDoctorCenterSetting>();
            this.FamilyDoctorMasters = new HashSet<FamilyDoctorMaster>();
            this.FamilyReferDetails = new HashSet<FamilyReferDetail>();
            this.FamilyReferMasters = new HashSet<FamilyReferMaster>();
            this.Hazinehs = new HashSet<Hazineh>();
            this.HISFamilyDocResponseDetails = new HashSet<HISFamilyDocResponseDetail>();
            this.IllnessFileDetails = new HashSet<IllnessFileDetail>();
            this.IllnessFileDetails1 = new HashSet<IllnessFileDetail>();
            this.IllnessFileDetails2 = new HashSet<IllnessFileDetail>();
            this.IllnessFileRequests = new HashSet<IllnessFileRequest>();
            this.IllnessFileRequests1 = new HashSet<IllnessFileRequest>();
            this.IllnessHistory_Compliant = new HashSet<IllnessHistory_Compliant>();
            this.IllnessHistory_Drug_Interaction = new HashSet<IllnessHistory_Drug_Interaction>();
            this.IllnessHistory_Drug_Use = new HashSet<IllnessHistory_Drug_Use>();
            this.IllnessHistory_Past = new HashSet<IllnessHistory_Past>();
            this.IllnessHistory_Surgery_Hospital = new HashSet<IllnessHistory_Surgery_Hospital>();
            this.info_K5 = new HashSet<info_K5>();
            this.Infoanbars = new HashSet<Infoanbar>();
            this.infoBanks = new HashSet<infoBank>();
            this.InfoBuyers = new HashSet<InfoBuyer>();
            this.InfoCashiers = new HashSet<InfoCashier>();
            this.infoDaroHasasiatzas = new HashSet<infoDaroHasasiatza>();
            this.infoDeviceLabs = new HashSet<infoDeviceLab>();
            this.infoDeviceLab_Coding = new HashSet<infoDeviceLab_Coding>();
            this.infoDoctor5 = new HashSet<infoDoctor5>();
            this.infodoctor8 = new HashSet<infodoctor8>();
            this.infoHazinehs = new HashSet<infoHazineh>();
            this.infoManagePics = new HashSet<infoManagePic>();
            this.InfoNobatComments = new HashSet<InfoNobatComment>();
            this.infoozvs = new HashSet<infoozv>();
            this.infopast_history = new HashSet<infopast_history>();
            this.infoProtocol_Mokamel_Detail1 = new HashSet<infoProtocol_Mokamel_Detail1>();
            this.infoProtocol_Mokamel_Detail2 = new HashSet<infoProtocol_Mokamel_Detail2>();
            this.infoProtocol_Mokamel_Detail4 = new HashSet<infoProtocol_Mokamel_Detail4>();
            this.infoProtocol_Mokamel_Detail5 = new HashSet<infoProtocol_Mokamel_Detail5>();
            this.infoProtocol_Mokamel_Master1 = new HashSet<infoProtocol_Mokamel_Master1>();
            this.infoProtocol_Mokamel_Master2 = new HashSet<infoProtocol_Mokamel_Master2>();
            this.infoProtocol_Mokamel_Master4 = new HashSet<infoProtocol_Mokamel_Master4>();
            this.InfoProtocolDetail8 = new HashSet<InfoProtocolDetail8>();
            this.InfoProtocolMaster2 = new HashSet<InfoProtocolMaster2>();
            this.InfoProtocolMaster4 = new HashSet<InfoProtocolMaster4>();
            this.InfoProtocolMaster8 = new HashSet<InfoProtocolMaster8>();
            this.infoprotocolMaterialMasters = new HashSet<infoprotocolMaterialMaster>();
            this.Infoquestions = new HashSet<Infoquestion>();
            this.InfoRadios = new HashSet<InfoRadio>();
            this.infoRepresenters = new HashSet<infoRepresenter>();
            this.InfoRequestGoods = new HashSet<InfoRequestGood>();
            this.InfoSection5 = new HashSet<InfoSection5>();
            this.InfoSemats = new HashSet<InfoSemat>();
            this.InfoService5_Section = new HashSet<InfoService5_Section>();
            this.InfoService5_SendToInsurDetail = new HashSet<InfoService5_SendToInsurDetail>();
            this.InfoService5_SendToInsurMaster = new HashSet<InfoService5_SendToInsurMaster>();
            this.infoService8 = new HashSet<infoService8>();
            this.Infospecials = new HashSet<Infospecial>();
            this.infotakhasos5 = new HashSet<infotakhasos5>();
            this.infotakhasos8 = new HashSet<infotakhasos8>();
            this.InfoTest_LBLPrintMaster = new HashSet<InfoTest_LBLPrintMaster>();
            this.infovisit1 = new HashSet<infovisit1>();
            this.infovisit5 = new HashSet<infovisit5>();
            this.insurs = new HashSet<insur>();
            this.InsurServices = new HashSet<InsurService>();
            this.kosordoctor5 = new HashSet<kosordoctor5>();
            this.Morakhasis = new HashSet<Morakhasi>();
            this.MsgRozanehDetails = new HashSet<MsgRozanehDetail>();
            this.NobatDetail1 = new HashSet<NobatDetail1>();
            this.OptionPicManages = new HashSet<OptionPicManage>();
            this.Payment_Software = new HashSet<Payment_Software>();
            this.Paziresh_nos_fizio = new HashSet<Paziresh_nos_fizio>();
            this.Paziresh2_DetailAntibiotic = new HashSet<Paziresh2_DetailAntibiotic>();
            this.Paziresh2_DetailResult = new HashSet<Paziresh2_DetailResult>();
            this.Paziresh2 = new HashSet<Paziresh2>();
            this.Paziresh3 = new HashSet<Paziresh3>();
            this.Paziresh5 = new HashSet<Paziresh5>();
            this.Paziresh8 = new HashSet<Paziresh8>();
            this.PersonalRahs = new HashSet<PersonalRah>();
            this.Questions = new HashSet<Question>();
            this.Queue_paz = new HashSet<Queue_paz>();
            this.QueueBakhshes = new HashSet<QueueBakhsh>();
            this.Recieve_Hoghogh = new HashSet<Recieve_Hoghogh>();
            this.RequestGoodDetails = new HashSet<RequestGoodDetail>();
            this.RequestGoodMasters = new HashSet<RequestGoodMaster>();
            this.Rule_serviceS = new HashSet<Rule_serviceS>();
            this.RulePaymentMasters = new HashSet<RulePaymentMaster>();
            this.Rulesaghf_baharan_master = new HashSet<Rulesaghf_baharan_master>();
            this.RuleSaghfFardi2 = new HashSet<RuleSaghfFardi2>();
            this.RuleSaghfFardi4 = new HashSet<RuleSaghfFardi4>();
            this.RuleSaghfFardi5 = new HashSet<RuleSaghfFardi5>();
            this.RuleSalaryMaster1_1175 = new HashSet<RuleSalaryMaster1_1175>();
            this.RuleSalaryMaster1 = new HashSet<RuleSalaryMaster1>();
            this.RuleSalaryMaster5_1056 = new HashSet<RuleSalaryMaster5_1056>();
            this.RuleSalaryMaster5 = new HashSet<RuleSalaryMaster5>();
            this.RuleSalaryMaster564 = new HashSet<RuleSalaryMaster564>();
            this.RuleSalaryMaster600 = new HashSet<RuleSalaryMaster600>();
            this.SelfDeclaration_Master = new HashSet<SelfDeclaration_Master>();
            this.SendBimehFizios = new HashSet<SendBimehFizio>();
            this.Service_just_one = new HashSet<Service_just_one>();
            this.Services = new HashSet<Service1>();
            this.upgrades = new HashSet<upgrade>();
            this.visitings = new HashSet<visiting>();
            this.visiting_transfer = new HashSet<visiting_transfer>();
        }
    
        public decimal Iduser { get; set; }
        public string nameuser { get; set; }
        public string date_create { get; set; }
        public string pass { get; set; }
        public string passadmin { get; set; }
        public Nullable<bool> passexpir { get; set; }
        public string fromdate { get; set; }
        public string Todate { get; set; }
        public string fromTime { get; set; }
        public string ToTime { get; set; }
        public Nullable<bool> fix { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string name_user { get; set; }
        public string date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<int> CenterID { get; set; }
        public Nullable<decimal> idsub { get; set; }
        public Nullable<decimal> idindex { get; set; }
        public Nullable<decimal> KindUser { get; set; }
        public string NodePtr { get; set; }
        public Nullable<bool> Checked { get; set; }
        public string IP { get; set; }
        public Nullable<int> MsgOn { get; set; }
        public Nullable<bool> Online { get; set; }
        public Nullable<bool> Arshad { get; set; }
        public Nullable<int> id_user_SMS { get; set; }
        public string mobile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuthUser> AuthUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasicUser> BasicUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calculate_Before_free_insur> Calculate_Before_free_insur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalenderMaster1> CalenderMaster1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalenderMaster5> CalenderMaster5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CenterSoftwarePeyGiri> CenterSoftwarePeyGiris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CenterSoftwarePeyGiri> CenterSoftwarePeyGiris1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceLab_Hitachi911Master> DeviceLab_Hitachi911Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceLab_Log> DeviceLab_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FamilyDoctorCenterSetting> FamilyDoctorCenterSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FamilyDoctorMaster> FamilyDoctorMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FamilyReferDetail> FamilyReferDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FamilyReferMaster> FamilyReferMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hazineh> Hazinehs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISFamilyDocResponseDetail> HISFamilyDocResponseDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IllnessFileDetail> IllnessFileDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IllnessFileDetail> IllnessFileDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IllnessFileDetail> IllnessFileDetails2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IllnessFileRequest> IllnessFileRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IllnessFileRequest> IllnessFileRequests1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IllnessHistory_Compliant> IllnessHistory_Compliant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IllnessHistory_Drug_Interaction> IllnessHistory_Drug_Interaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IllnessHistory_Drug_Use> IllnessHistory_Drug_Use { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IllnessHistory_Past> IllnessHistory_Past { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IllnessHistory_Surgery_Hospital> IllnessHistory_Surgery_Hospital { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<info_K5> info_K5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Infoanbar> Infoanbars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoBank> infoBanks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoBuyer> InfoBuyers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoCashier> InfoCashiers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoDaroHasasiatza> infoDaroHasasiatzas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoDeviceLab> infoDeviceLabs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoDeviceLab_Coding> infoDeviceLab_Coding { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoDoctor5> infoDoctor5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infodoctor8> infodoctor8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoHazineh> infoHazinehs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoManagePic> infoManagePics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoNobatComment> InfoNobatComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoozv> infoozvs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infopast_history> infopast_history { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoProtocol_Mokamel_Detail1> infoProtocol_Mokamel_Detail1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoProtocol_Mokamel_Detail2> infoProtocol_Mokamel_Detail2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoProtocol_Mokamel_Detail4> infoProtocol_Mokamel_Detail4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoProtocol_Mokamel_Detail5> infoProtocol_Mokamel_Detail5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoProtocol_Mokamel_Master1> infoProtocol_Mokamel_Master1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoProtocol_Mokamel_Master2> infoProtocol_Mokamel_Master2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoProtocol_Mokamel_Master4> infoProtocol_Mokamel_Master4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoProtocolDetail8> InfoProtocolDetail8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoProtocolMaster2> InfoProtocolMaster2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoProtocolMaster4> InfoProtocolMaster4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoProtocolMaster8> InfoProtocolMaster8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoprotocolMaterialMaster> infoprotocolMaterialMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Infoquestion> Infoquestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoRadio> InfoRadios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoRepresenter> infoRepresenters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoRequestGood> InfoRequestGoods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoSection5> InfoSection5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoSemat> InfoSemats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoService5_Section> InfoService5_Section { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoService5_SendToInsurDetail> InfoService5_SendToInsurDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoService5_SendToInsurMaster> InfoService5_SendToInsurMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoService8> infoService8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Infospecial> Infospecials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infotakhasos5> infotakhasos5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infotakhasos8> infotakhasos8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoTest_LBLPrintMaster> InfoTest_LBLPrintMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infovisit1> infovisit1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infovisit5> infovisit5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<insur> insurs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsurService> InsurServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kosordoctor5> kosordoctor5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Morakhasi> Morakhasis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MsgRozanehDetail> MsgRozanehDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NobatDetail1> NobatDetail1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OptionPicManage> OptionPicManages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment_Software> Payment_Software { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paziresh_nos_fizio> Paziresh_nos_fizio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paziresh2_DetailAntibiotic> Paziresh2_DetailAntibiotic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paziresh2_DetailResult> Paziresh2_DetailResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paziresh2> Paziresh2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paziresh3> Paziresh3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paziresh5> Paziresh5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paziresh8> Paziresh8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalRah> PersonalRahs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question> Questions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Queue_paz> Queue_paz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QueueBakhsh> QueueBakhshes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recieve_Hoghogh> Recieve_Hoghogh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestGoodDetail> RequestGoodDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestGoodMaster> RequestGoodMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rule_serviceS> Rule_serviceS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RulePaymentMaster> RulePaymentMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rulesaghf_baharan_master> Rulesaghf_baharan_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleSaghfFardi2> RuleSaghfFardi2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleSaghfFardi4> RuleSaghfFardi4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleSaghfFardi5> RuleSaghfFardi5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleSalaryMaster1_1175> RuleSalaryMaster1_1175 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleSalaryMaster1> RuleSalaryMaster1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleSalaryMaster5_1056> RuleSalaryMaster5_1056 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleSalaryMaster5> RuleSalaryMaster5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleSalaryMaster564> RuleSalaryMaster564 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleSalaryMaster600> RuleSalaryMaster600 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SelfDeclaration_Master> SelfDeclaration_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SendBimehFizio> SendBimehFizios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_just_one> Service_just_one { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service1> Services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<upgrade> upgrades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visiting> visitings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visiting_transfer> visiting_transfer { get; set; }
    }
}
