//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoMaterial
    {
        public Nullable<decimal> idsub { get; set; }
        public string namematerial { get; set; }
        public string unitmaterial { get; set; }
        public Nullable<float> ace_order { get; set; }
        public Nullable<float> limit_ace { get; set; }
        public Nullable<float> Mojodi { get; set; }
        public Nullable<decimal> idindex { get; set; }
        public string NodePtr { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string name_user { get; set; }
        public string date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<bool> @checked { get; set; }
        public Nullable<int> CenterID { get; set; }
        public Nullable<double> Count_default { get; set; }
        public Nullable<decimal> Price { get; set; }
        public decimal ID { get; set; }
        public string IDMaterialNew { get; set; }
    
        public virtual infoCenteral infoCenteral { get; set; }
    }
}
