//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Key
    {
        public int id { get; set; }
        public string Text { get; set; }
        public Nullable<int> KeyBoardID { get; set; }
        public string Handler { get; set; }
        public Nullable<int> Keyvalue { get; set; }
        public Nullable<int> Row { get; set; }
        public Nullable<int> Column { get; set; }
        public string Style { get; set; }
        public string ButtonMessage { get; set; }
    }
}
