//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeyBoard
    {
        public int id { get; set; }
        public string KeyboardName { get; set; }
        public string KeyBoardType { get; set; }
        public Nullable<int> KeyBoardID { get; set; }
        public Nullable<int> RelatedPage { get; set; }
        public string Handler { get; set; }
        public string KeyboardText { get; set; }
    }
}
