//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lab_illness
    {
        public int KindID { get; set; }
        public int CenterID { get; set; }
        public int id_illness { get; set; }
        public int RowID { get; set; }
        public int id_Lab { get; set; }
        public Nullable<int> Type { get; set; }
        public string dateLab { get; set; }
        public string ResultLab { get; set; }
        public string Normal { get; set; }
        public Nullable<int> currentRow { get; set; }
    }
}
