//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Listkar
    {
        public decimal code { get; set; }
        public decimal RowID { get; set; }
        public string descript { get; set; }
        public Nullable<decimal> code_lab { get; set; }
        public Nullable<int> CenterID { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<decimal> Idauto { get; set; }
        public Nullable<bool> is_radif { get; set; }
        public Nullable<bool> is_age { get; set; }
        public Nullable<bool> is_name { get; set; }
        public Nullable<int> font_size { get; set; }
        public Nullable<decimal> width_columns { get; set; }
        public Nullable<byte> flag_port_land { get; set; }
        public Nullable<decimal> width_namesick { get; set; }
        public Nullable<decimal> width_columns_Dos { get; set; }
        public Nullable<decimal> width_namesick_Dos { get; set; }
    
        public virtual infoCenteral infoCenteral { get; set; }
    }
}
