//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class mab_k_jarahi_bihoshi
    {
        public decimal kindid { get; set; }
        public decimal rowid { get; set; }
        public Nullable<decimal> jarahi_dolati { get; set; }
        public Nullable<decimal> jarahi_khososi { get; set; }
        public Nullable<decimal> jarahi_tarefe1 { get; set; }
        public Nullable<decimal> jarahi_tarefe2 { get; set; }
        public Nullable<decimal> bihoshi_dolati { get; set; }
        public Nullable<decimal> bihoshi_khososi { get; set; }
        public Nullable<decimal> bihoshi_tarefe1 { get; set; }
        public Nullable<decimal> bihoshi_tarefe2 { get; set; }
        public Nullable<decimal> id_insur { get; set; }
        public string date_edit { get; set; }
        public string time_edit { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string from_date { get; set; }
        public string to_date { get; set; }
        public Nullable<decimal> jarahi_tarefe3 { get; set; }
        public Nullable<decimal> jarahi_tarefe4 { get; set; }
        public Nullable<decimal> bihoshi_tarefe3 { get; set; }
        public Nullable<decimal> bihoshi_tarefe4 { get; set; }
    }
}
