//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maliyat_master
    {
        public decimal Serial { get; set; }
        public string Date { get; set; }
        public Nullable<byte> Flag_Service_Soft { get; set; }
        public Nullable<decimal> From_RecNo { get; set; }
        public Nullable<decimal> To_RecNo { get; set; }
        public string FLname { get; set; }
        public string IDEghtesadi { get; set; }
        public string Melicode { get; set; }
        public string Ostan { get; set; }
        public string shahrestan { get; set; }
        public string Code_posti { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string date_edit { get; set; }
        public string time_edit { get; set; }
        public Nullable<decimal> code_sherkat { get; set; }
    }
}
