//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maliyat_detail
    {
        public decimal ID { get; set; }
        public decimal Serial_Master { get; set; }
        public Nullable<decimal> id_software { get; set; }
        public Nullable<decimal> Mab_kol { get; set; }
        public Nullable<decimal> Mab_takhfif { get; set; }
        public Nullable<decimal> Sum_mab_kol { get; set; }
        public string Comment { get; set; }
        public Nullable<decimal> Varizi1 { get; set; }
        public Nullable<decimal> Varizi2 { get; set; }
        public Nullable<decimal> khales_varizi { get; set; }
        public string comment1 { get; set; }
        public string comment2 { get; set; }
        public string comment3 { get; set; }
        public string name_service { get; set; }
        public string sign_kasr1 { get; set; }
        public string sign_kasr2 { get; set; }
        public Nullable<decimal> kasr_varizi1 { get; set; }
        public Nullable<decimal> kasr_varizi2 { get; set; }
        public string comment_kasr1 { get; set; }
        public string comment_kasr2 { get; set; }
        public Nullable<decimal> mab_batel { get; set; }
        public string unit_name { get; set; }
        public Nullable<decimal> mab_unit { get; set; }
        public Nullable<decimal> mab_maliyat { get; set; }
        public Nullable<decimal> mab_kol_after_takhfif { get; set; }
    }
}
