//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class managerlab
    {
        public decimal code { get; set; }
        public decimal rowid { get; set; }
        public Nullable<bool> defult { get; set; }
        public string name_manage { get; set; }
        public Nullable<decimal> kindid { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<int> CenterID { get; set; }
        public string lastname_manage { get; set; }
        public string codeNezam_manager { get; set; }
        public Nullable<bool> @checked { get; set; }
    
        public virtual infoCenteral infoCenteral { get; set; }
    }
}
