//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterKharid
    {
        public decimal CodeSys { get; set; }
        public decimal RowID { get; set; }
        public decimal ID_SoftWare { get; set; }
        public decimal vahedid { get; set; }
        public decimal CurrentRow { get; set; }
        public Nullable<decimal> ID_User { get; set; }
        public string Date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<int> Cancel_Flag { get; set; }
        public Nullable<decimal> idauto { get; set; }
        public Nullable<decimal> Id_UserDelete { get; set; }
        public Nullable<System.DateTime> Date_Delete { get; set; }
        public string CodeKharid { get; set; }
        public string Date_Kharid { get; set; }
        public Nullable<decimal> CodeCompany { get; set; }
        public string CodeEkht { get; set; }
        public Nullable<decimal> Mab_Curr { get; set; }
        public Nullable<decimal> Mab_calc { get; set; }
        public Nullable<decimal> Takhfif { get; set; }
        public Nullable<decimal> Countaglam { get; set; }
        public Nullable<decimal> Mab_maliat { get; set; }
        public string Comment { get; set; }
        public Nullable<decimal> Mab_Comment { get; set; }
        public Nullable<decimal> flagEdited { get; set; }
    }
}
