//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class medic_rest
    {
        public decimal kindid { get; set; }
        public Nullable<decimal> id_illness { get; set; }
        public string from_date { get; set; }
        public string to_date { get; set; }
        public Nullable<decimal> to_ezam { get; set; }
        public string sick_comment { get; set; }
        public string doctor_name { get; set; }
        public Nullable<decimal> id_amaliyat { get; set; }
        public Nullable<byte> flag_rest { get; set; }
        public Nullable<decimal> kindid_ezam { get; set; }
        public string date_ezam { get; set; }
    }
}
