//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class mMedicalHistory_Detail3
    {
        public decimal id_illness { get; set; }
        public int RowID { get; set; }
        public Nullable<int> Code_Cause { get; set; }
    
        public virtual mtarhdarman2_Master mtarhdarman2_Master { get; set; }
    }
}
