//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motalebat
    {
        public decimal idauto { get; set; }
        public Nullable<int> CenterID { get; set; }
        public Nullable<decimal> id_insur { get; set; }
        public string date_daryaft { get; set; }
        public Nullable<decimal> Mab_daryaft { get; set; }
        public Nullable<decimal> Mab_kosor { get; set; }
        public Nullable<decimal> Mab_Maliat { get; set; }
        public string descript { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string name_user { get; set; }
        public string date_Edit { get; set; }
        public string Time_Edit { get; set; }
    
        public virtual infoCenteral infoCenteral { get; set; }
    }
}
