//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtarhdarman2_Service_detail
    {
        public decimal id_illness { get; set; }
        public decimal RowIDRep { get; set; }
        public decimal RowID { get; set; }
        public decimal id_service { get; set; }
        public string t1 { get; set; }
        public string t2 { get; set; }
        public string t3 { get; set; }
        public string t4 { get; set; }
    
        public virtual mtarhdarman2_Section_Detail mtarhdarman2_Section_Detail { get; set; }
    }
}
