//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nobat_delete
    {
        public decimal IDauto { get; set; }
        public Nullable<decimal> RowID { get; set; }
        public decimal IDvisit { get; set; }
        public string datevisit { get; set; }
        public string Timevisit { get; set; }
        public string t1 { get; set; }
        public string t2 { get; set; }
        public string t3 { get; set; }
        public string t4 { get; set; }
        public Nullable<decimal> idvisitprev { get; set; }
        public string datevisitprev { get; set; }
        public Nullable<decimal> ID_sick { get; set; }
        public Nullable<decimal> ID_service { get; set; }
        public string duration { get; set; }
        public Nullable<decimal> ID_dentist { get; set; }
        public string dayvisit { get; set; }
        public Nullable<int> number_dayvisit { get; set; }
        public Nullable<decimal> ID_Tashkish { get; set; }
        public Nullable<decimal> id_operation { get; set; }
        public Nullable<decimal> id_insur_Sick { get; set; }
        public Nullable<decimal> id_insur2 { get; set; }
        public Nullable<decimal> id_niro2 { get; set; }
        public Nullable<decimal> id_status2 { get; set; }
        public Nullable<decimal> id_nesbat2 { get; set; }
        public string date_Paziresh { get; set; }
        public string Time_Paziresh { get; set; }
        public Nullable<int> per_workdo { get; set; }
        public Nullable<int> percent_total { get; set; }
        public Nullable<bool> flag_hazineh { get; set; }
        public Nullable<bool> flag_daryaft_hazineh { get; set; }
        public Nullable<bool> flag_delete { get; set; }
        public string comment { get; set; }
        public string vaz { get; set; }
        public Nullable<decimal> PageNo { get; set; }
        public Nullable<decimal> id_Ebtal { get; set; }
        public Nullable<byte> Cancel_Flag { get; set; }
        public Nullable<byte> CurrentRow { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string name_user { get; set; }
        public string date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<decimal> id_user_Per_work { get; set; }
        public string D_EFF_Per_work { get; set; }
        public string date_delete { get; set; }
        public Nullable<int> CenterID { get; set; }
    }
}
