//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nobat7
    {
        public decimal IDauto { get; set; }
        public Nullable<decimal> RowID { get; set; }
        public Nullable<decimal> IDnobat { get; set; }
        public string datenobat { get; set; }
        public string Timenobat { get; set; }
        public Nullable<decimal> ID_sick { get; set; }
        public Nullable<decimal> ID_service { get; set; }
        public Nullable<decimal> ID_doctor { get; set; }
        public string dayvisit { get; set; }
        public Nullable<int> number_dayvisit { get; set; }
        public string date_Paziresh { get; set; }
        public string comment { get; set; }
        public Nullable<decimal> id_Ebtal { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public string lname { get; set; }
        public string fname { get; set; }
        public string tel { get; set; }
        public Nullable<int> shift { get; set; }
        public Nullable<int> sex { get; set; }
        public Nullable<decimal> kindidrel_visit { get; set; }
        public Nullable<byte> tel_hozor { get; set; }
        public string code_bimeh { get; set; }
        public Nullable<byte> elam_hozor { get; set; }
    }
}
