//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class NobatDetail1Delete
    {
        public decimal ID { get; set; }
        public decimal ID_NobatMaster { get; set; }
        public Nullable<int> RowID { get; set; }
        public Nullable<decimal> id_illness { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string TimeNobat { get; set; }
        public Nullable<decimal> id_service { get; set; }
        public int ID_TypeNobat { get; set; }
        public string tel { get; set; }
        public Nullable<int> Shift { get; set; }
        public Nullable<byte> Sex { get; set; }
        public string Comment { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<byte> id_Cancel { get; set; }
        public Nullable<decimal> id_user_Cancel { get; set; }
        public string Date_Edit_Cancel { get; set; }
        public string Time_Edit_Cancel { get; set; }
        public Nullable<decimal> kindidrel { get; set; }
        public Nullable<byte> send_sms { get; set; }
        public Nullable<byte> SMSResult { get; set; }
        public Nullable<bool> IsCalledQueue { get; set; }
        public string D_CalledQueue { get; set; }
        public string T_CalledQueue { get; set; }
        public Nullable<byte> Active_NotActive { get; set; }
        public string comment_cancel { get; set; }
    }
}
