//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionPicManage
    {
        public decimal ID { get; set; }
        public Nullable<int> Tabindex { get; set; }
        public Nullable<int> CenterID { get; set; }
        public string HostFTP { get; set; }
        public Nullable<int> PortFTP { get; set; }
        public string UIDFTP { get; set; }
        public string PIDFTP { get; set; }
        public Nullable<bool> PassiveFTP { get; set; }
        public string HostProxyFTP { get; set; }
        public Nullable<int> PortProxyFTP { get; set; }
        public string UIDProxyFTP { get; set; }
        public string PIDProxyFTP { get; set; }
        public Nullable<int> FTP_Share { get; set; }
        public string FTPDir { get; set; }
        public string ShareDir { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string Date_Edit { get; set; }
        public string Time_Edit { get; set; }
    
        public virtual infoCenteral infoCenteral { get; set; }
        public virtual Infouser Infouser { get; set; }
    }
}
