//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public string Product_Url { get; set; }
        public string Product_Detail { get; set; }
        public Nullable<long> Telegram_Id { get; set; }
        public Nullable<int> Order_State { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public short Finished { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public string DesignAndColor { get; set; }
        public string OrderSize { get; set; }
        public Nullable<long> OrderImageID { get; set; }
        public Nullable<int> InvoiceGroup { get; set; }
        public Nullable<int> PriceLir { get; set; }
        public Nullable<int> PriceToman { get; set; }
        public Nullable<int> Paid { get; set; }
    }
}
