//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Par_Dar
    {
        public decimal idSanad { get; set; }
        public string dat { get; set; }
        public Nullable<decimal> id_dentist_Per { get; set; }
        public Nullable<decimal> Mab { get; set; }
        public Nullable<decimal> id_Cause { get; set; }
        public Nullable<decimal> flag { get; set; }
        public string no_check { get; set; }
        public string dat_check { get; set; }
        public string bank { get; set; }
        public string shobeh { get; set; }
        public string no_fish { get; set; }
        public Nullable<int> flaging { get; set; }
        public Nullable<bool> dentist_Personel { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> Par_Dar1 { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string name_user { get; set; }
        public string date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<int> CenterID { get; set; }
    
        public virtual infoCenteral infoCenteral { get; set; }
    }
}
