//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paziresh7
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paziresh7()
        {
            this.Paziresh7_Detail = new HashSet<Paziresh7_Detail>();
        }
    
        public decimal kindidrel { get; set; }
        public decimal kindid { get; set; }
        public decimal rowid { get; set; }
        public byte flag_paziresh { get; set; }
        public decimal ID_service { get; set; }
        public string datevisit { get; set; }
        public int id_paziresh { get; set; }
        public Nullable<decimal> id_illness { get; set; }
        public string date_etabar { get; set; }
        public string date_Noskheh { get; set; }
        public Nullable<int> PageNo { get; set; }
        public Nullable<decimal> id_doctor { get; set; }
        public Nullable<decimal> id_do { get; set; }
        public Nullable<decimal> id_takhasos { get; set; }
        public Nullable<decimal> id_doc_bihoshi { get; set; }
        public Nullable<decimal> id_tecn_bihoshi { get; set; }
        public Nullable<decimal> id_asist_bihoshi { get; set; }
        public Nullable<decimal> id_komak_jarah { get; set; }
        public Nullable<decimal> id_surgery_nurse { get; set; }
        public Nullable<decimal> id_aid_nurse { get; set; }
        public Nullable<int> id_insur_illness { get; set; }
        public Nullable<int> id_niro { get; set; }
        public Nullable<int> id_nesbat { get; set; }
        public Nullable<int> id_status { get; set; }
        public Nullable<int> id_insur_CalCulate { get; set; }
        public Nullable<decimal> id_insur_mokamel { get; set; }
        public Nullable<decimal> mab_insur_mokamel { get; set; }
        public Nullable<decimal> mab_ok_org { get; set; }
        public Nullable<decimal> Mab_illness { get; set; }
        public Nullable<decimal> Mab_Org { get; set; }
        public Nullable<decimal> mab_service { get; set; }
        public Nullable<decimal> Mab_ghabel_daryaft { get; set; }
        public Nullable<decimal> Mab_daryafti { get; set; }
        public Nullable<decimal> Mandeh { get; set; }
        public Nullable<decimal> mab_jarahi { get; set; }
        public Nullable<decimal> mab_bihoshi { get; set; }
        public Nullable<decimal> mab_komak_jarah { get; set; }
        public Nullable<decimal> mab_otagh_amal { get; set; }
        public Nullable<decimal> mab_recovery { get; set; }
        public Nullable<decimal> Mab_yaraneh_illness_grp { get; set; }
        public Nullable<decimal> Mab_yaraneh_illness_frd { get; set; }
        public Nullable<decimal> Mab_yaraneh_Additional_grp { get; set; }
        public Nullable<decimal> Mab_yaraneh_Additional_frd { get; set; }
        public Nullable<decimal> Mab_takhfif_Clinic_grp { get; set; }
        public Nullable<decimal> Mab_takhfif_Clinic_frd { get; set; }
        public Nullable<decimal> Mab_takhfif_doctor_grp { get; set; }
        public Nullable<decimal> Mab_takhfif_doctor_frd { get; set; }
        public Nullable<decimal> SUM_Mab_material { get; set; }
        public Nullable<decimal> SUM_Mab_drug { get; set; }
        public Nullable<decimal> SUM_ghabeldaryaft_Material { get; set; }
        public Nullable<decimal> SUM_ghabeldaryaft_Drug { get; set; }
        public Nullable<decimal> SUM_Mab_yaraneh_material { get; set; }
        public Nullable<decimal> SUM_Mab_yaraneh_drug { get; set; }
        public Nullable<decimal> SUM_Mab_takhfif_material { get; set; }
        public Nullable<decimal> SUM_Mab_takhfif_drug { get; set; }
        public string F_time { get; set; }
        public string T_time { get; set; }
        public string duration { get; set; }
        public Nullable<int> kind_bihoshi { get; set; }
        public string mail_no { get; set; }
        public Nullable<int> kind_EYE { get; set; }
        public Nullable<decimal> Mab_Additional_Col { get; set; }
        public Nullable<int> id_user { get; set; }
        public string date_edit { get; set; }
        public string time_edit { get; set; }
        public Nullable<int> CountPrint { get; set; }
        public Nullable<bool> flag_daryaft_hazineh { get; set; }
        public Nullable<byte> Kind_Paziresh { get; set; }
        public Nullable<int> Kind_daftar { get; set; }
        public Nullable<int> CenterID { get; set; }
        public Nullable<bool> is_round { get; set; }
        public Nullable<decimal> Mab_Round { get; set; }
        public Nullable<decimal> Mab_Back { get; set; }
        public Nullable<decimal> groupid { get; set; }
        public Nullable<decimal> id_section { get; set; }
        public Nullable<decimal> id_User_deleteRow { get; set; }
        public string Comment { get; set; }
        public Nullable<decimal> Mab_yaraneh_illness_frd_drug { get; set; }
        public Nullable<decimal> Mab_yaraneh_Additional_frd_drug { get; set; }
        public Nullable<decimal> Mab_takhfif_Clinic_frd_drug { get; set; }
        public Nullable<decimal> Mab_yaraneh_illness_frd_masrafi { get; set; }
        public Nullable<decimal> Mab_yaraneh_Additional_frd_masrafi { get; set; }
        public Nullable<decimal> Mab_takhfif_Clinic_frd_masrafi { get; set; }
        public Nullable<decimal> identifier { get; set; }
        public Nullable<decimal> mab_variance_bihoshi { get; set; }
        public Nullable<decimal> mab_variance_jarahi { get; set; }
        public Nullable<decimal> ruleid_mokamel { get; set; }
        public Nullable<decimal> ruleid { get; set; }
        public Nullable<decimal> mab_illness_mokamel { get; set; }
        public Nullable<decimal> max_mab_insur_mokamel { get; set; }
        public Nullable<decimal> mab_jarahi_mokamel { get; set; }
        public Nullable<decimal> mab_bihoshi_mokamel { get; set; }
        public Nullable<decimal> mab_komak_jarah_mokamel { get; set; }
        public Nullable<decimal> mab_otagh_amal_mokamel { get; set; }
        public Nullable<decimal> mab_recovery_mokamel { get; set; }
        public string time_paziresh { get; set; }
        public string time_bastary { get; set; }
        public string date_bastary { get; set; }
        public string time_tarkhis { get; set; }
        public string date_tarkhis { get; set; }
        public Nullable<int> user_tarkhis { get; set; }
        public Nullable<int> user_bastary { get; set; }
        public Nullable<decimal> per_insur_mokamel { get; set; }
        public Nullable<decimal> mab_variance_bihoshi_mokamel { get; set; }
        public Nullable<decimal> mab_variance_jarahi_mokamel { get; set; }
        public Nullable<byte> flag_mokamel_manual { get; set; }
        public Nullable<decimal> var_komak_jarah { get; set; }
        public Nullable<decimal> var_otagh_amal { get; set; }
        public Nullable<decimal> var_recovery { get; set; }
        public Nullable<decimal> var_komak_jarah_mokamel { get; set; }
        public Nullable<decimal> var_otagh_amal_mokamel { get; set; }
        public Nullable<decimal> var_recovery_mokamel { get; set; }
        public Nullable<decimal> misID { get; set; }
    
        public virtual infoCenteral infoCenteral { get; set; }
        public virtual paziresh7_descript paziresh7_descript { get; set; }
        public virtual paziresh7_protocol paziresh7_protocol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paziresh7_Detail> Paziresh7_Detail { get; set; }
    }
}
