//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paziresh8
    {
        public decimal KindidRel { get; set; }
        public string datevisit { get; set; }
        public Nullable<int> id_paziresh { get; set; }
        public Nullable<decimal> id_illness { get; set; }
        public string date_etabar { get; set; }
        public string date_Noskheh { get; set; }
        public Nullable<int> PageNo { get; set; }
        public string CodeNezam_doctor { get; set; }
        public Nullable<int> id_do_Fizio_karshenas { get; set; }
        public Nullable<decimal> id_insur_illness { get; set; }
        public Nullable<decimal> id_niro { get; set; }
        public Nullable<decimal> id_nesbat { get; set; }
        public Nullable<decimal> id_status { get; set; }
        public Nullable<decimal> id_insur_CalCulate { get; set; }
        public Nullable<int> Tedad_Ozv { get; set; }
        public Nullable<int> Tedad_Darkhast { get; set; }
        public Nullable<int> Tedad_Hozor { get; set; }
        public Nullable<decimal> Mab_Service_Col { get; set; }
        public Nullable<decimal> Mab_illness_Col { get; set; }
        public Nullable<decimal> Mab_Additional_Col { get; set; }
        public Nullable<decimal> Mab_Org_Col { get; set; }
        public Nullable<decimal> Mab_ghabel_daryaft { get; set; }
        public Nullable<decimal> Mab_daryafti { get; set; }
        public Nullable<decimal> Mandeh { get; set; }
        public Nullable<decimal> Mab_yaraneh_illness_Col { get; set; }
        public Nullable<decimal> Mab_yaraneh_Additional_Col { get; set; }
        public Nullable<decimal> Mab_takhfif_Clinic_Col { get; set; }
        public Nullable<decimal> Mab_takhfif_doctor_Col { get; set; }
        public Nullable<decimal> Mab_takhfif_Clinic_frd { get; set; }
        public Nullable<decimal> Mab_takhfif_doctor_frd { get; set; }
        public Nullable<bool> flag_daryaft_hazineh { get; set; }
        public Nullable<byte> Kind_Paziresh { get; set; }
        public Nullable<int> Kind_daftar { get; set; }
        public Nullable<int> CenterID { get; set; }
        public Nullable<bool> is_round { get; set; }
        public Nullable<decimal> Mab_Round { get; set; }
        public Nullable<decimal> Mab_Back { get; set; }
        public string CodeRah { get; set; }
        public Nullable<int> CountPrint { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string date_edit { get; set; }
        public string time_edit { get; set; }
        public string date_noskhe_last { get; set; }
        public string comment { get; set; }
        public Nullable<decimal> Tedad_Hozor_New { get; set; }
        public Nullable<decimal> misID { get; set; }
    
        public virtual infoCenteral infoCenteral { get; set; }
        public virtual infodoctor8 infodoctor8 { get; set; }
        public virtual infonesbat infonesbat { get; set; }
        public virtual infoniro infoniro { get; set; }
        public virtual InfoSick InfoSick { get; set; }
        public virtual InfoStatu InfoStatu { get; set; }
        public virtual Infouser Infouser { get; set; }
        public virtual insur insur { get; set; }
        public virtual insur insur1 { get; set; }
        public virtual Paziresh8 Paziresh81 { get; set; }
        public virtual Paziresh8 Paziresh82 { get; set; }
    }
}
