//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paziresh3_detail
    {
        public decimal KindID { get; set; }
        public int RowID { get; set; }
        public int Code { get; set; }
        public Nullable<decimal> Mab_illness { get; set; }
        public Nullable<decimal> Mab_Org { get; set; }
        public Nullable<decimal> Mab_ghabel_daryaft_illnessRec { get; set; }
        public Nullable<decimal> Mab_taahod { get; set; }
        public Nullable<decimal> Mab_takhfif_Clinic_grp { get; set; }
        public Nullable<decimal> Mab_yaraneh_illness_grp { get; set; }
        public Nullable<decimal> Mab_yaraneh_Additional_grp { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Price_Change { get; set; }
        public Nullable<int> CodeChange { get; set; }
        public Nullable<decimal> Cntdrug { get; set; }
        public Nullable<int> id_Insur_Calculate { get; set; }
        public Nullable<float> CntdrugChange { get; set; }
        public Nullable<byte> flg_hagfaniorg { get; set; }
        public Nullable<decimal> Mab_takhfif_doctor_grp { get; set; }
        public decimal KindidRel { get; set; }
        public Nullable<decimal> code_anbar { get; set; }
        public Nullable<decimal> ID_SazmanOnline { get; set; }
        public Nullable<byte> send_bimeh { get; set; }
        public Nullable<decimal> id_user_send { get; set; }
    
        public virtual Paziresh3 Paziresh3 { get; set; }
    }
}
