//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paziresh4_detail1
    {
        public int KindID { get; set; }
        public int RowID { get; set; }
        public int Code { get; set; }
        public Nullable<decimal> Mab_ghabel_daryaft_illnessRec { get; set; }
        public Nullable<int> id_Insur_Calculate { get; set; }
        public Nullable<decimal> Mab_takhfif_Clinic_grp { get; set; }
        public Nullable<decimal> Mab_takhfif_doctor_grp { get; set; }
        public Nullable<decimal> Mab_yaraneh_illness_grp { get; set; }
        public Nullable<decimal> Mab_yaraneh_Additional_grp { get; set; }
        public Nullable<decimal> Mab_illness { get; set; }
        public Nullable<decimal> Mab_Org { get; set; }
        public Nullable<int> Codegroup { get; set; }
        public Nullable<byte> OKResult { get; set; }
        public Nullable<byte> ALLResult { get; set; }
        public Nullable<byte> NotResult { get; set; }
        public Nullable<byte> impossibleResult { get; set; }
        public Nullable<int> id_UserResult { get; set; }
        public string D_Result { get; set; }
        public string Time_Result { get; set; }
        public string D_Printed { get; set; }
        public Nullable<byte> Printed { get; set; }
        public Nullable<decimal> tarefeye_Bime { get; set; }
        public Nullable<decimal> mab_variance_illness { get; set; }
        public Nullable<decimal> mab_variance_org { get; set; }
        public Nullable<decimal> id_section { get; set; }
        public decimal KindidRel { get; set; }
        public Nullable<decimal> id_insur_mokamel { get; set; }
        public Nullable<decimal> mab_insur_mokamel_illness { get; set; }
        public Nullable<decimal> mab_insur_mokamel_additional { get; set; }
        public Nullable<decimal> mab_insur_mokamel { get; set; }
        public Nullable<byte> free_sys { get; set; }
        public Nullable<decimal> add_zone { get; set; }
        public Nullable<decimal> mab_from_saghf { get; set; }
        public Nullable<decimal> ruleid_saghf { get; set; }
        public Nullable<decimal> from_saghf_illness { get; set; }
        public Nullable<decimal> from_saghf_material { get; set; }
        public Nullable<decimal> from_saghf_lab { get; set; }
        public Nullable<decimal> from_saghf_additional { get; set; }
        public Nullable<byte> send_bimeh { get; set; }
        public Nullable<decimal> id_user_send { get; set; }
        public Nullable<decimal> mab_service_mokamel { get; set; }
        public Nullable<decimal> mab_illness_mokamel { get; set; }
        public Nullable<decimal> mab_illness_mkl_param { get; set; }
        public Nullable<decimal> mab_additional_mkl_param { get; set; }
        public Nullable<decimal> diff_illness_mkl { get; set; }
        public Nullable<decimal> diff_additional_mkl { get; set; }
        public Nullable<decimal> id_smartCard { get; set; }
        public Nullable<int> count_Service { get; set; }
    
        public virtual InfoRadio InfoRadio { get; set; }
        public virtual Paziresh4 Paziresh4 { get; set; }
    }
}
