//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class paziresh7_protocol
    {
        public decimal kindidrel { get; set; }
        public Nullable<int> RuleID { get; set; }
        public Nullable<int> id_insur { get; set; }
        public Nullable<bool> Checked { get; set; }
        public Nullable<int> per_illness { get; set; }
        public Nullable<int> per_org { get; set; }
        public Nullable<decimal> per_komak_jarah { get; set; }
        public Nullable<byte> kind_komak_jarah { get; set; }
        public Nullable<decimal> per_otagh_amal { get; set; }
        public Nullable<byte> kind_otagh_amal { get; set; }
        public Nullable<decimal> per_recovery { get; set; }
        public Nullable<byte> kind_recovery { get; set; }
        public Nullable<decimal> cnt_k_jarahi { get; set; }
        public Nullable<decimal> cnt_k_bihoshi { get; set; }
        public Nullable<int> time_dure_bihoshi { get; set; }
        public Nullable<decimal> mab_col { get; set; }
        public Nullable<decimal> tarefe_sayer { get; set; }
        public Nullable<int> per_insur_mokamel_pro { get; set; }
        public Nullable<decimal> max_mab_insur_mokamel_pro { get; set; }
        public Nullable<decimal> mab_insur_mokamel_pro { get; set; }
    
        public virtual Paziresh7 Paziresh7 { get; set; }
    }
}
