//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class paziresh7_descript
    {
        public decimal kindidrel { get; set; }
        public string descript_bihoshi { get; set; }
        public string descript_jarahi { get; set; }
    
        public virtual Paziresh7 Paziresh7 { get; set; }
    }
}
