//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paziresh_nos_fizio
    {
        public decimal KindidRel { get; set; }
        public int CenterID { get; set; }
        public int ID_SoftWare { get; set; }
        public decimal KindID { get; set; }
        public decimal RowID { get; set; }
        public Nullable<decimal> idvisit { get; set; }
        public string datevisit { get; set; }
        public Nullable<decimal> ID_Section { get; set; }
        public decimal id_service { get; set; }
        public string FromDate { get; set; }
        public string Todate { get; set; }
        public string FromTime { get; set; }
        public string ToTime { get; set; }
        public Nullable<int> ID_doctor { get; set; }
        public Nullable<int> id_do { get; set; }
        public Nullable<decimal> ID_illness { get; set; }
        public string CodeBimeh { get; set; }
        public Nullable<decimal> ID_Insur_illness { get; set; }
        public Nullable<decimal> ID_Insur2 { get; set; }
        public Nullable<decimal> ID_Niro { get; set; }
        public Nullable<decimal> ID_Nesbat { get; set; }
        public Nullable<decimal> ID_Status { get; set; }
        public Nullable<decimal> id_Insur_Calculate { get; set; }
        public Nullable<decimal> Mab_illness { get; set; }
        public Nullable<decimal> Mab_Org { get; set; }
        public Nullable<decimal> Mab_ghabel_daryaft { get; set; }
        public Nullable<decimal> Mab_daryafti { get; set; }
        public Nullable<decimal> Mandeh { get; set; }
        public Nullable<decimal> Mab_takhfif_doctor_grp { get; set; }
        public Nullable<decimal> Mab_takhfif_Clinic_grp { get; set; }
        public Nullable<decimal> Mab_takhfif_doctor_frd { get; set; }
        public Nullable<decimal> Mab_takhfif_Clinic_frd { get; set; }
        public Nullable<decimal> Mab_yaraneh_illness_grp { get; set; }
        public Nullable<decimal> Mab_yaraneh_Additional_grp { get; set; }
        public Nullable<decimal> Mab_yaraneh_illness_frd { get; set; }
        public Nullable<decimal> Mab_yaraneh_Additional_frd { get; set; }
        public Nullable<decimal> Mab_Additional_Col { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> Checked { get; set; }
        public Nullable<int> CountNobat { get; set; }
        public Nullable<bool> flag_daryaft_hazineh { get; set; }
        public string date_Etabar { get; set; }
        public string date_Noskheh { get; set; }
        public Nullable<decimal> PageNo { get; set; }
        public Nullable<decimal> CurrentRow { get; set; }
        public Nullable<decimal> ID_User { get; set; }
        public string Date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<int> Cancel_Flag { get; set; }
        public Nullable<int> id_InsurMokamel { get; set; }
        public Nullable<decimal> Mab_Org_Mokamel { get; set; }
        public Nullable<decimal> Mab_illness_Mokamel { get; set; }
        public Nullable<int> Count_Service { get; set; }
        public Nullable<decimal> mab_back { get; set; }
        public Nullable<decimal> mab_round { get; set; }
        public Nullable<decimal> mab_variance_illness { get; set; }
        public Nullable<decimal> mab_variance_org { get; set; }
        public Nullable<bool> is_round { get; set; }
        public Nullable<int> groupid { get; set; }
        public Nullable<int> PrintCount { get; set; }
        public Nullable<decimal> IDSazman { get; set; }
        public Nullable<decimal> Online_Mab_Illness { get; set; }
        public Nullable<decimal> Online_Mab_Org { get; set; }
        public Nullable<decimal> Online_Mab_Service { get; set; }
        public Nullable<decimal> Online_Tedad_Mojaz_tajviz { get; set; }
        public Nullable<decimal> additional_round { get; set; }
        public Nullable<decimal> cnt_k { get; set; }
        public Nullable<decimal> mab_org_mokamel_extra { get; set; }
        public Nullable<byte> free_sys { get; set; }
        public Nullable<decimal> mab_from_saghf { get; set; }
        public Nullable<decimal> ruleid_saghf { get; set; }
        public Nullable<decimal> from_saghf_illness { get; set; }
        public Nullable<decimal> from_saghf_additional { get; set; }
        public Nullable<decimal> id_user_delete { get; set; }
        public Nullable<decimal> add_zone { get; set; }
        public Nullable<byte> send_bimeh { get; set; }
        public Nullable<decimal> id_user_send { get; set; }
        public Nullable<decimal> mab_service_mokamel { get; set; }
        public Nullable<decimal> mab_illness_mkl_param_col { get; set; }
        public Nullable<decimal> mab_additional_mkl_param_col { get; set; }
        public Nullable<decimal> diff_illness_mkl_col { get; set; }
        public Nullable<decimal> diff_additional_mkl_col { get; set; }
        public Nullable<decimal> count_setion_taghaza { get; set; }
        public Nullable<decimal> count_setion_erae { get; set; }
        public Nullable<decimal> id_ozv { get; set; }
        public string time_paziresh { get; set; }
        public Nullable<byte> Flag_fizio { get; set; }
        public string First_date_fizio { get; set; }
        public string Last_date_fizio { get; set; }
    
        public virtual Grp_Master Grp_Master { get; set; }
        public virtual infoCenteral infoCenteral { get; set; }
        public virtual infoozv infoozv { get; set; }
        public virtual InfoSection5 InfoSection5 { get; set; }
        public virtual InfoService5 InfoService5 { get; set; }
        public virtual Infouser Infouser { get; set; }
        public virtual insur insur { get; set; }
    }
}
