//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paziresh4_detail2
    {
        public int KindID { get; set; }
        public int RowID { get; set; }
        public int Code { get; set; }
        public int CodeMaterial { get; set; }
        public Nullable<decimal> Size { get; set; }
        public decimal KindidRel { get; set; }
    
        public virtual Paziresh4 Paziresh4 { get; set; }
    }
}
