//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public decimal idCode { get; set; }
        public Nullable<decimal> IdSubCode { get; set; }
        public string FNamePer { get; set; }
        public string LNamePer { get; set; }
        public string Grade { get; set; }
        public string Tel { get; set; }
        public string addr { get; set; }
        public string CodeMeli { get; set; }
        public string date_ijad { get; set; }
        public string date_employ { get; set; }
        public string father { get; set; }
        public string SS { get; set; }
        public string Madrak { get; set; }
        public string sabegeh { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string name_user { get; set; }
        public string date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<int> CenterID { get; set; }
    }
}
