//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class personel_enter_outgo
    {
        public int id { get; set; }
        public string date_edit { get; set; }
        public string time_enter { get; set; }
        public string time_exit { get; set; }
        public string time_diff { get; set; }
        public Nullable<int> id_typework { get; set; }
        public Nullable<decimal> id_per { get; set; }
    
        public virtual InfoTypework InfoTypework { get; set; }
        public virtual Personel_info Personel_info { get; set; }
    }
}
