//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalRah
    {
        public decimal kindid { get; set; }
        public string ID_personal { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string code_bimeh { get; set; }
        public Nullable<decimal> id_insur { get; set; }
        public Nullable<decimal> id_nesbat { get; set; }
        public Nullable<decimal> id_niro { get; set; }
        public Nullable<decimal> id_status { get; set; }
        public string date_sabt { get; set; }
        public string time_edit { get; set; }
        public string date_edit { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string sex { get; set; }
    
        public virtual infonesbat infonesbat { get; set; }
        public virtual infoniro infoniro { get; set; }
        public virtual InfoStatu InfoStatu { get; set; }
        public virtual Infouser Infouser { get; set; }
        public virtual insur insur { get; set; }
    }
}
