//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public decimal idauto { get; set; }
        public Nullable<decimal> id_sick { get; set; }
        public Nullable<decimal> id_visit { get; set; }
        public string date_visit { get; set; }
        public string Part { get; set; }
        public byte[] imagesick { get; set; }
        public Nullable<int> CenterID { get; set; }
    
        public virtual infoCenteral infoCenteral { get; set; }
    }
}
