//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Protocol_Pardakht
    {
        public decimal IDauto { get; set; }
        public string @object { get; set; }
        public string Eblagh { get; set; }
        public string date_Eblagh { get; set; }
        public string date_run { get; set; }
        public string date_expir { get; set; }
        public Nullable<decimal> id_sick { get; set; }
        public Nullable<decimal> id_service { get; set; }
        public Nullable<decimal> id_khedmat { get; set; }
        public Nullable<decimal> id_insur { get; set; }
        public Nullable<decimal> id_power { get; set; }
        public string nesbat { get; set; }
        public Nullable<decimal> id_dentist { get; set; }
        public Nullable<float> Per_dentist { get; set; }
        public Nullable<float> Per_org { get; set; }
        public Nullable<float> Per_total { get; set; }
        public Nullable<bool> flag_dentist { get; set; }
        public Nullable<bool> flag_org { get; set; }
        public Nullable<bool> act { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string name_user { get; set; }
        public string date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<int> CenterID { get; set; }
    }
}
