//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class protocol7_detail
    {
        public int RuleID { get; set; }
        public int RowID { get; set; }
        public int ID_Service { get; set; }
        public int id_takhasos { get; set; }
        public Nullable<bool> Checked { get; set; }
        public Nullable<int> id_User { get; set; }
        public string Date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<System.DateTime> Date_Delete { get; set; }
        public Nullable<int> Id_UserDelete { get; set; }
    }
}
