//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Protocol_Ph_Mokamel
    {
        public decimal KindID { get; set; }
        public Nullable<int> id_insur_mokamel { get; set; }
        public string D_Run { get; set; }
        public string D_Expire { get; set; }
        public double Per_Org_mokamel_M { get; set; }
        public Nullable<bool> Ctrl_Privatedoc { get; set; }
        public Nullable<decimal> Top_Specialdoc { get; set; }
        public Nullable<decimal> Top_Piblicdoc { get; set; }
        public Nullable<decimal> Top_dentist { get; set; }
        public string FileNameBimeh { get; set; }
        public Nullable<decimal> id_Private { get; set; }
        public Nullable<decimal> id_formal { get; set; }
        public Nullable<bool> hagfan { get; set; }
        public Nullable<int> CenterID { get; set; }
        public Nullable<int> id_user { get; set; }
        public string date_edit { get; set; }
        public string time_edit { get; set; }
        public Nullable<byte> FlagDelEdit { get; set; }
        public Nullable<decimal> Mama_Mab { get; set; }
        public Nullable<decimal> dentist_Mab { get; set; }
        public Nullable<decimal> code_markaz { get; set; }
        public Nullable<decimal> Max_Mab_Bimeh_M { get; set; }
    }
}
