//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Protocol_Detail_Mokamel
    {
        public int RuleID { get; set; }
        public int CenterID { get; set; }
        public int RowID { get; set; }
        public int id_insur_Mokamel { get; set; }
        public decimal Per_illness { get; set; }
        public Nullable<decimal> Max_Mab_illness { get; set; }
        public Nullable<int> CurrentRow { get; set; }
        public Nullable<bool> Checked { get; set; }
        public Nullable<int> id_User { get; set; }
        public string Date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<System.DateTime> Date_Delete { get; set; }
        public Nullable<int> Id_UserDelete { get; set; }
        public Nullable<int> Cancel_Flag { get; set; }
        public string Cancel_FlagDate { get; set; }
    }
}
