//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class RadioMaterialMasrafi
    {
        public int Code { get; set; }
        public int RowID { get; set; }
        public Nullable<int> CodeMaterial { get; set; }
        public Nullable<decimal> Size { get; set; }
    
        public virtual InfoRadio InfoRadio { get; set; }
        public virtual RadioMaterial RadioMaterial { get; set; }
    }
}
