//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class range_master
    {
        public decimal kindid { get; set; }
        public decimal rowid { get; set; }
        public Nullable<decimal> code { get; set; }
        public Nullable<int> CenterID { get; set; }
        public Nullable<decimal> ID_User { get; set; }
        public string Date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<decimal> ID_UserDelete { get; set; }
        public string date_delete { get; set; }
        public string Time_delete { get; set; }
        public Nullable<bool> @checked { get; set; }
    }
}
