//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reciept
    {
        public int id { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Receipt_Image_ID { get; set; }
        public Nullable<long> Telegram_Id { get; set; }
        public string Payment_Id { get; set; }
        public short Finished { get; set; }
        public string Subject { get; set; }
        public Nullable<System.DateTime> ReciptTime { get; set; }
    }
}
