//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reminder_detail
    {
        public decimal kindid { get; set; }
        public decimal id_user { get; set; }
        public string time_Reminder { get; set; }
        public string time_snooz { get; set; }
        public Nullable<bool> flag_takmil { get; set; }
    }
}
