//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reminder
    {
        public decimal id_illness { get; set; }
        public decimal RowID { get; set; }
        public string Nameillness { get; set; }
        public string dat { get; set; }
        public string descript { get; set; }
        public Nullable<bool> active { get; set; }
        public string ID_UserS { get; set; }
        public string date_Edit { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> CenterID { get; set; }
        public decimal kindid { get; set; }
        public string hour { get; set; }
        public Nullable<int> flag_takmil { get; set; }
    }
}
