//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class report
    {
        public decimal idauto { get; set; }
        public decimal KindID { get; set; }
        public string Kindreport { get; set; }
        public string titlereport { get; set; }
        public string Caption { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public string FieldName { get; set; }
        public string FontName { get; set; }
        public Nullable<int> SizeFont { get; set; }
        public bool Bold { get; set; }
        public string Paper { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string date_Edit { get; set; }
        public string Time_Edit { get; set; }
    }
}
