//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class RuleSaghfgrp_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RuleSaghfgrp_Master()
        {
            this.RuleSaghfgrp_Insur = new HashSet<RuleSaghfgrp_Insur>();
            this.RuleSaghfgrp_Niro = new HashSet<RuleSaghfgrp_Niro>();
            this.RuleSaghfgrp_Status = new HashSet<RuleSaghfgrp_Status>();
        }
    
        public decimal ID { get; set; }
        public string Header { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public Nullable<decimal> Mab_Saghf { get; set; }
        public Nullable<int> id_FieldNameControl { get; set; }
        public Nullable<int> id_RuleSaghfInfo { get; set; }
        public string CommentAlarm { get; set; }
        public Nullable<decimal> id_illness { get; set; }
        public Nullable<int> id_Group { get; set; }
        public Nullable<float> percent_transfer { get; set; }
        public Nullable<byte> flag_khanevar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleSaghfgrp_Insur> RuleSaghfgrp_Insur { get; set; }
        public virtual RuleSaghfInfo RuleSaghfInfo { get; set; }
        public virtual RuleSaghfInfoFieldNameControl RuleSaghfInfoFieldNameControl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleSaghfgrp_Niro> RuleSaghfgrp_Niro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleSaghfgrp_Status> RuleSaghfgrp_Status { get; set; }
    }
}
