//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class RulePaymentDetail
    {
        public decimal ID { get; set; }
        public Nullable<decimal> ID_RuleIDMaster { get; set; }
        public Nullable<int> CenterID { get; set; }
        public string D_Run { get; set; }
        public string D_Expire { get; set; }
        public Nullable<decimal> Id_software { get; set; }
        public Nullable<decimal> per_pardakht { get; set; }
    
        public virtual infoCenteral infoCenteral { get; set; }
        public virtual RulePaymentMaster RulePaymentMaster { get; set; }
    }
}
