//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class RuleSaghfgrp_Status
    {
        public decimal ID { get; set; }
        public Nullable<decimal> ID_RuleSaghfgrp_Master { get; set; }
        public Nullable<decimal> id_status { get; set; }
    
        public virtual RuleSaghfgrp_Master RuleSaghfgrp_Master { get; set; }
    }
}
