//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class RulesaghfService
    {
        public int RuleID { get; set; }
        public int RowID { get; set; }
        public int CenterID { get; set; }
        public string D_Run { get; set; }
        public string D_Expire { get; set; }
        public Nullable<int> id_niro { get; set; }
        public Nullable<int> id_nesbat { get; set; }
        public Nullable<int> id_status { get; set; }
        public Nullable<decimal> saghfinsur_Mounth { get; set; }
        public Nullable<decimal> saghfinsur_Sal { get; set; }
        public Nullable<decimal> saghf_sarparast { get; set; }
        public Nullable<decimal> saghf_every_aele { get; set; }
        public Nullable<int> saghf_every_aele_Cnt { get; set; }
        public Nullable<decimal> saghf_All_aele { get; set; }
        public Nullable<int> saghf_All_aele_Cnt { get; set; }
        public Nullable<decimal> saghf_every_khanevar { get; set; }
        public Nullable<int> id_software { get; set; }
        public Nullable<int> id_user { get; set; }
        public string date_edit { get; set; }
        public string time_edit { get; set; }
        public Nullable<bool> Flag_illness { get; set; }
        public Nullable<bool> Flag_additional { get; set; }
        public Nullable<bool> Flag_material { get; set; }
        public Nullable<bool> Flag_lab { get; set; }
        public Nullable<byte> kind_illness { get; set; }
        public Nullable<byte> kind_additional { get; set; }
        public Nullable<byte> kind_material { get; set; }
        public Nullable<byte> kind_lab { get; set; }
        public Nullable<byte> flag_kind_rule { get; set; }
        public Nullable<byte> free_ehtesab { get; set; }
        public Nullable<decimal> per_takhfif_illness { get; set; }
        public Nullable<decimal> per_takhfif_material { get; set; }
        public Nullable<decimal> per_takhfif_lab { get; set; }
        public Nullable<decimal> per_takhfif_additional { get; set; }
    }
}
