//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rule_salary
    {
        public decimal KindID { get; set; }
        public decimal RowID { get; set; }
        public int ID_SoftWare { get; set; }
        public string D_Run { get; set; }
        public string D_Expire { get; set; }
        public Nullable<decimal> workgroup { get; set; }
        public Nullable<byte> Do_doctor { get; set; }
        public Nullable<bool> holiday { get; set; }
        public Nullable<byte> kind_cnt_mab { get; set; }
        public Nullable<decimal> Fservice_cnt_mab { get; set; }
        public Nullable<decimal> TOservice_cnt_mab { get; set; }
        public Nullable<bool> IS_Mab_Service { get; set; }
        public Nullable<bool> IS_Mab_Additional { get; set; }
        public Nullable<bool> IS_Mab_Material { get; set; }
        public Nullable<bool> IS_Mab_Lab { get; set; }
        public Nullable<byte> per_mab { get; set; }
        public Nullable<decimal> per_mab_value { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public decimal idauto { get; set; }
        public string f_time { get; set; }
        public string T_time { get; set; }
    }
}
