//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class RuleSalaryDetail600
    {
        public decimal ID { get; set; }
        public Nullable<decimal> ID_RuleSalaryMaster600 { get; set; }
        public decimal id_service { get; set; }
        public int id_shift { get; set; }
        public Nullable<decimal> Per_FromMab_Service { get; set; }
        public Nullable<decimal> Per_FromMab_Lab { get; set; }
        public Nullable<decimal> Per_FromMab_Material { get; set; }
        public Nullable<decimal> Per_FromMab_Additional { get; set; }
        public Nullable<decimal> Per_FromMab_Service_holiday { get; set; }
        public Nullable<decimal> Per_FromMab_Lab_holiday { get; set; }
        public Nullable<decimal> Per_FromMab_Material_holiday { get; set; }
        public Nullable<decimal> Per_FromMab_Additional_holiday { get; set; }
        public Nullable<decimal> id_dentist { get; set; }
    
        public virtual Infodentist Infodentist { get; set; }
        public virtual infoService infoService { get; set; }
        public virtual InfoShift InfoShift { get; set; }
        public virtual RuleSalaryMaster600 RuleSalaryMaster600 { get; set; }
    }
}
