//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class RulePazireshLab
    {
        public decimal KindID { get; set; }
        public decimal RowID { get; set; }
        public int CenterID { get; set; }
        public Nullable<decimal> ID_Insur { get; set; }
        public Nullable<decimal> Cnt_Paz { get; set; }
        public Nullable<decimal> Day_Paz { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<int> CurrentRow { get; set; }
        public Nullable<decimal> Cancel_Flag { get; set; }
        public decimal idauto { get; set; }
        public string D_Run { get; set; }
        public string D_Expire { get; set; }
        public Nullable<decimal> ID_Makharej { get; set; }
        public Nullable<bool> FreeRule { get; set; }
        public Nullable<decimal> Fage { get; set; }
        public Nullable<decimal> Tage { get; set; }
        public Nullable<decimal> cnt_makharej { get; set; }
        public Nullable<decimal> id_niro { get; set; }
    }
}
