//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class rule_show_msg
    {
        public decimal ruleid { get; set; }
        public decimal rowid { get; set; }
        public string from_date { get; set; }
        public string to_date { get; set; }
        public Nullable<decimal> id_insur { get; set; }
        public Nullable<decimal> id_nesbat { get; set; }
        public Nullable<decimal> id_niro { get; set; }
        public Nullable<decimal> id_status { get; set; }
        public Nullable<byte> show_msg_to { get; set; }
        public string comment { get; set; }
        public Nullable<byte> id_software { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string date_edit { get; set; }
        public string time_edit { get; set; }
        public Nullable<int> CenterID { get; set; }
        public Nullable<decimal> id_Section { get; set; }
        public Nullable<decimal> id_insur_mokamel { get; set; }
    }
}
