//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rule
    {
        public int CenterID { get; set; }
        public int ID { get; set; }
        public int RowID { get; set; }
        public int Code1 { get; set; }
        public int flag { get; set; }
        public Nullable<int> Code2 { get; set; }
        public Nullable<int> Code3 { get; set; }
        public string descript { get; set; }
        public Nullable<int> CurrentRow { get; set; }
        public Nullable<bool> Checked { get; set; }
        public Nullable<int> id_User { get; set; }
        public string Date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<System.DateTime> Date_Delete { get; set; }
        public Nullable<int> Id_UserDelete { get; set; }
        public Nullable<int> Cancel_Flag { get; set; }
        public string Cancel_FlagDate { get; set; }
        public Nullable<bool> Mamno { get; set; }
        public Nullable<bool> tosie { get; set; }
        public Nullable<int> mamnofrom { get; set; }
        public Nullable<int> mamnoto { get; set; }
        public Nullable<int> tosiefrom { get; set; }
        public Nullable<int> tosieto { get; set; }
        public Nullable<int> CodeDarokahesh { get; set; }
        public Nullable<int> CodeDaroAfzayesh { get; set; }
        public Nullable<int> mamnoTajviz { get; set; }
        public Nullable<int> tosiehtajviz { get; set; }
    }
}
