//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rule_Salary_assistant
    {
        public decimal id_rule { get; set; }
        public string Date_run { get; set; }
        public string Date_expire { get; set; }
        public Nullable<double> per_gharardad { get; set; }
        public Nullable<double> per_maliat { get; set; }
        public Nullable<decimal> id_type_assistant { get; set; }
        public Nullable<decimal> userId { get; set; }
        public string Date_edit { get; set; }
        public string Time_edit { get; set; }
        public Nullable<int> centerid { get; set; }
        public Nullable<decimal> id_bakhsh { get; set; }
    
        public virtual Assistant Assistant { get; set; }
    }
}
