//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelfDeclaration_Quesion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SelfDeclaration_Quesion()
        {
            this.SelfDeclaration_Detail = new HashSet<SelfDeclaration_Detail>();
        }
    
        public int Code { get; set; }
        public string descript { get; set; }
        public Nullable<bool> En_Disable { get; set; }
        public Nullable<bool> Result_Yes { get; set; }
        public Nullable<bool> Result_No { get; set; }
        public Nullable<bool> Checked { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string date_Edit { get; set; }
        public string Time_Edit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SelfDeclaration_Detail> SelfDeclaration_Detail { get; set; }
    }
}
