//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendDiskdental1
    {
        public string coderah { get; set; }
        public Nullable<decimal> id_smartcard { get; set; }
        public Nullable<int> centerid { get; set; }
        public Nullable<decimal> rowidsort { get; set; }
        public int radif { get; set; }
        public int rd_page { get; set; }
        public Nullable<decimal> id_sick { get; set; }
        public Nullable<decimal> id_dentist { get; set; }
        public string LnameSick { get; set; }
        public string fnameSick { get; set; }
        public string namesick { get; set; }
        public string nameservice { get; set; }
        public string namedentist { get; set; }
        public string namecenteral { get; set; }
        public Nullable<int> Sum_Mab_Noshkhes { get; set; }
        public Nullable<int> Mab_Noshkhes_Org { get; set; }
        public Nullable<int> Mab_Noshkhes_illness { get; set; }
        public string pre_codesend { get; set; }
        public Nullable<decimal> kindidrel { get; set; }
        public Nullable<int> IsSend_Material2Insur { get; set; }
        public Nullable<int> IsSend_Lab2Insur { get; set; }
        public Nullable<decimal> id_service { get; set; }
        public Nullable<decimal> id_insur { get; set; }
        public Nullable<decimal> id_Niro { get; set; }
        public string codesend { get; set; }
        public string T1 { get; set; }
        public string T2 { get; set; }
        public string T3 { get; set; }
        public string T4 { get; set; }
        public int mab_service_base { get; set; }
        public int mab_service { get; set; }
        public int mab_org { get; set; }
        public int mab_illness { get; set; }
        public int mab_lab { get; set; }
        public int mab_lab_org { get; set; }
        public int mab_lab_illness { get; set; }
        public int mab_material { get; set; }
        public int mab_material_org { get; set; }
        public int mab_material_illness { get; set; }
        public string datevisit { get; set; }
        public string DateNosKheh { get; set; }
        public string Expire_daftar { get; set; }
        public Nullable<decimal> PageNo { get; set; }
        public Nullable<decimal> Code_Nezam { get; set; }
        public string dddd { get; set; }
        public string Code_Bimeh { get; set; }
        public Nullable<int> Count_Mab_Service_TO_Zero { get; set; }
        public Nullable<int> Count_CodeSend { get; set; }
        public Nullable<int> Invalid_CodeSend { get; set; }
        public int Tedad_Nosakh { get; set; }
        public Nullable<decimal> CodeSender { get; set; }
        public Nullable<int> sex { get; set; }
        public Nullable<int> id_TypeService { get; set; }
        public string codeinternational_103 { get; set; }
        public string codeinternational_104 { get; set; }
        public string codeinternational_105 { get; set; }
        public string codeinternational_other { get; set; }
        public Nullable<int> count_dent { get; set; }
    }
}
