//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Group_detail
    {
        public decimal ID { get; set; }
        public Nullable<decimal> ID_master { get; set; }
        public Nullable<decimal> id_service { get; set; }
    
        public virtual Service_Group_Master Service_Group_Master { get; set; }
    }
}
