//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service11
    {
        public int CenterId { get; set; }
        public int Id_section { get; set; }
        public int Code { get; set; }
        public int RowId { get; set; }
        public string CodeManual { get; set; }
        public Nullable<int> Idsub { get; set; }
        public string Nameservice { get; set; }
        public string LatinName { get; set; }
        public string ekhtesari { get; set; }
        public string CodeSend { get; set; }
        public Nullable<int> CurrentRow { get; set; }
        public Nullable<int> Cancel_flag { get; set; }
        public Nullable<bool> @checked { get; set; }
        public Nullable<int> Id_user { get; set; }
        public string date_edit { get; set; }
        public string time_edit { get; set; }
        public Nullable<System.DateTime> date_delete { get; set; }
        public Nullable<int> id_userDelete { get; set; }
        public Nullable<int> fix { get; set; }
        public Nullable<int> id_takhasos { get; set; }
        public string nodePtr { get; set; }
    }
}
