//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class service7
    {
        public int Code { get; set; }
        public string CodeManual { get; set; }
        public Nullable<int> Idsub { get; set; }
        public string Nameservice { get; set; }
        public string nodePtr { get; set; }
        public Nullable<decimal> count_k_jarahi { get; set; }
        public Nullable<bool> @checked { get; set; }
        public Nullable<int> Id_user { get; set; }
        public string date_edit { get; set; }
        public string time_edit { get; set; }
        public Nullable<System.DateTime> date_delete { get; set; }
        public Nullable<int> id_userDelete { get; set; }
        public Nullable<decimal> count_k_bihoshi { get; set; }
    }
}
