//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Group_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service_Group_Master()
        {
            this.Service_Group_detail = new HashSet<Service_Group_detail>();
        }
    
        public decimal ID { get; set; }
        public Nullable<decimal> id_insur { get; set; }
        public Nullable<decimal> id_service { get; set; }
        public Nullable<int> id_software { get; set; }
        public Nullable<int> centerid { get; set; }
        public string date_edit { get; set; }
        public string time_edit { get; set; }
        public Nullable<decimal> id_user { get; set; }
    
        public virtual infoCenteral infoCenteral { get; set; }
        public virtual InfoSoftware InfoSoftware { get; set; }
        public virtual insur insur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_Group_detail> Service_Group_detail { get; set; }
    }
}
