//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceMab
    {
        public int KindID { get; set; }
        public int Centeralid { get; set; }
        public int ID_Section { get; set; }
        public int RowID { get; set; }
        public int ID_Service { get; set; }
        public Nullable<decimal> Mab_dolati { get; set; }
        public Nullable<decimal> Mab_khososi { get; set; }
        public Nullable<decimal> Mab_v1 { get; set; }
        public Nullable<decimal> Mab_v2 { get; set; }
        public string D_Run { get; set; }
        public string D_Expire { get; set; }
        public Nullable<int> id_takhasos { get; set; }
        public Nullable<int> Cancel_Flag { get; set; }
        public Nullable<bool> Checked { get; set; }
        public Nullable<int> id_user { get; set; }
        public string date_edit { get; set; }
        public string time_edit { get; set; }
        public Nullable<System.DateTime> date_delete { get; set; }
        public Nullable<int> id_userDelete { get; set; }
        public Nullable<int> CurrentRow { get; set; }
        public Nullable<int> Id_ServiceSection { get; set; }
    }
}
