//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSSendBox
    {
        public decimal ID { get; set; }
        public string TextSend { get; set; }
        public string Number { get; set; }
        public string D_Edit { get; set; }
        public string T_Edit { get; set; }
        public string D_Start { get; set; }
        public string T_Start { get; set; }
        public string D_Sent { get; set; }
        public string T_Sent { get; set; }
        public Nullable<int> ID_StatusSend { get; set; }
        public Nullable<int> ID_HISUsersBaseLog { get; set; }
        public Nullable<decimal> ID_TBL { get; set; }
    }
}
