//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportDetail1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupportDetail1()
        {
            this.SupportDetail3 = new HashSet<SupportDetail3>();
        }
    
        public decimal ID { get; set; }
        public Nullable<decimal> IDInfoCompany { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public Nullable<decimal> Mab { get; set; }
        public Nullable<bool> FreeSupport { get; set; }
        public string Date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<int> id_User { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> tasviyeh { get; set; }
    
        public virtual InfoCompany InfoCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupportDetail3> SupportDetail3 { get; set; }
    }
}
