//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taeed_Rec
    {
        public decimal ID { get; set; }
        public Nullable<decimal> id_do { get; set; }
        public Nullable<decimal> id_software { get; set; }
        public Nullable<decimal> recno { get; set; }
        public Nullable<decimal> kindidrel { get; set; }
        public Nullable<byte> flag_taeed { get; set; }
        public string comment_not_taeed { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string date_edit { get; set; }
        public string time_edit { get; set; }
        public Nullable<byte> flag_taeed_avaliye { get; set; }
        public string comment_avaliye { get; set; }
        public Nullable<decimal> cnt_change { get; set; }
    }
}
