//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class takhfif_Detail_Center
    {
        public decimal code { get; set; }
        public Nullable<int> RuleID_takhfif { get; set; }
        public Nullable<int> centerid { get; set; }
    
        public virtual infoCenteral infoCenteral { get; set; }
    }
}
