//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class takhasos_illness
    {
        public int KindID { get; set; }
        public int CenterID { get; set; }
        public int id_illness { get; set; }
        public int RowID { get; set; }
        public string Family_savabegh { get; set; }
        public string Sick_savabegh { get; set; }
        public string Sensitive { get; set; }
        public Nullable<int> Etiyad { get; set; }
        public string daro_savabegh { get; set; }
        public string descript { get; set; }
        public string Period_bardari { get; set; }
        public Nullable<int> Cnt_zayman { get; set; }
        public string BloodGroup { get; set; }
        public string Date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<int> id_User { get; set; }
        public Nullable<int> CurrentRow { get; set; }
        public Nullable<int> Cancel_Flag { get; set; }
    }
}
