//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarhgraph
    {
        public decimal ID_Illness { get; set; }
        public decimal RowID { get; set; }
        public int Adult_Primary { get; set; }
        public Nullable<int> NumberDental { get; set; }
        public string DO { get; set; }
        public string descript { get; set; }
        public Nullable<int> CurrentRow { get; set; }
        public string date_edit { get; set; }
        public string time_edit { get; set; }
        public Nullable<decimal> ID_User { get; set; }
        public Nullable<int> CenterID { get; set; }
    }
}
