//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class tashkhi
    {
        public int KindID { get; set; }
        public int id_illness { get; set; }
        public short RowID { get; set; }
        public Nullable<decimal> id_dentist { get; set; }
        public string date_tash { get; set; }
        public string ElatMorajeh { get; set; }
        public string AdatKhas { get; set; }
        public string Systemic { get; set; }
        public string sabeghehdaro { get; set; }
        public string zayeatdahan { get; set; }
        public string Moayenehdandan { get; set; }
        public string zayeatdandan { get; set; }
        public string descript { get; set; }
        public string Bakhshha { get; set; }
        public string date_edit { get; set; }
        public string time_edit { get; set; }
        public Nullable<byte> CurrentRow { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> CenterID { get; set; }
    
        public virtual infoCenteral infoCenteral { get; set; }
    }
}
