//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class tel
    {
        public decimal idkind { get; set; }
        public Nullable<decimal> IDSub { get; set; }
        public string descript { get; set; }
        public string Tel1 { get; set; }
        public string MB { get; set; }
        public Nullable<bool> fix { get; set; }
        public Nullable<decimal> idindex { get; set; }
        public string NodePtr { get; set; }
        public Nullable<bool> Checked { get; set; }
        public string ZipCode { get; set; }
        public string Comment { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public string date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<int> CenterID { get; set; }
    
        public virtual infoCenteral infoCenteral { get; set; }
    }
}
