//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestDetail1
    {
        public decimal Code { get; set; }
        public decimal RowIDDetail1 { get; set; }
        public int CenterID { get; set; }
        public string D_Run { get; set; }
        public string D_Expire { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<int> Fage { get; set; }
        public Nullable<int> Tage { get; set; }
        public string LimitUp { get; set; }
        public string LimitDown { get; set; }
        public string LimitUpMojaz { get; set; }
        public string LimitDownMojaz { get; set; }
        public Nullable<int> Bardar { get; set; }
        public string descript { get; set; }
        public Nullable<int> CurrentRow { get; set; }
        public Nullable<decimal> ID_User { get; set; }
        public string Date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<decimal> ID_UserDelete { get; set; }
        public Nullable<System.DateTime> date_delete { get; set; }
        public Nullable<int> F_mnt { get; set; }
        public Nullable<int> To_mnt { get; set; }
        public Nullable<int> F_day { get; set; }
        public Nullable<int> To_day { get; set; }
    
        public virtual infoCenteral infoCenteral { get; set; }
    }
}
