//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCommandState
    {
        public int id { get; set; }
        public Nullable<long> TelegramAssignedID { get; set; }
        public Nullable<int> LastState { get; set; }
        public Nullable<int> CurrentState { get; set; }
        public string LastAnswer { get; set; }
        public Nullable<System.DateTime> LastActionTime { get; set; }
        public string CurrentFunctionHandler { get; set; }
        public Nullable<int> LastPage { get; set; }
        public Nullable<int> NextState { get; set; }
    }
}
