//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int id { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public string TelegramFirstName { get; set; }
        public string TelegramLastName { get; set; }
        public string UserTelegramID { get; set; }
        public Nullable<long> TelegramAssignedID { get; set; }
        public string MobileNo { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> ShopCheeID { get; set; }
        public Nullable<short> Finished { get; set; }
        public string Reagent { get; set; }
    }
}
