//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class visiting_mokamel_detail
    {
        public decimal kindidrel { get; set; }
        public Nullable<decimal> mab_up_illness_mkl { get; set; }
        public Nullable<decimal> mab_up_material_mkl { get; set; }
        public Nullable<decimal> mab_up_lab_mkl { get; set; }
        public Nullable<decimal> mab_up_additional_mkl { get; set; }
        public Nullable<decimal> per_from_illness_mkl { get; set; }
        public Nullable<decimal> per_from_material_mkl { get; set; }
        public Nullable<decimal> per_from_lab_mkl { get; set; }
        public Nullable<decimal> per_from_additional_mkl { get; set; }
        public Nullable<decimal> mab_org_mokamel_illness_col { get; set; }
        public Nullable<decimal> mab_org_mokamel_material_col { get; set; }
        public Nullable<decimal> mab_org_mokamel_lab_col { get; set; }
        public Nullable<decimal> mab_org_mokamel_additional_col { get; set; }
        public Nullable<decimal> mab_from_saghf { get; set; }
        public Nullable<decimal> ruleid_saghf { get; set; }
        public Nullable<decimal> from_saghf_illness { get; set; }
        public Nullable<decimal> from_saghf_material { get; set; }
        public Nullable<decimal> from_saghf_lab { get; set; }
        public Nullable<decimal> from_saghf_additional { get; set; }
        public Nullable<decimal> mab_illness_mkl_param_col { get; set; }
        public Nullable<decimal> mab_material_mkl_param_col { get; set; }
        public Nullable<decimal> mab_lab_mkl_param_col { get; set; }
        public Nullable<decimal> mab_additional_mkl_param_col { get; set; }
        public Nullable<decimal> diff_illness_mkl_col { get; set; }
        public Nullable<decimal> diff_material_mkl_col { get; set; }
        public Nullable<decimal> diff_lab_mkl_col { get; set; }
        public Nullable<decimal> diff_additional_mkl_col { get; set; }
        public Nullable<decimal> mab_service_mokamel { get; set; }
        public Nullable<decimal> mab_illness_mokamel { get; set; }
        public Nullable<decimal> mab_from_saghf_grp { get; set; }
        public Nullable<decimal> ruleid_saghf_grp { get; set; }
        public Nullable<decimal> from_saghf_illness_grp { get; set; }
        public Nullable<decimal> from_saghf_material_grp { get; set; }
        public Nullable<decimal> from_saghf_lab_grp { get; set; }
        public Nullable<decimal> from_saghf_additional_grp { get; set; }
        public Nullable<decimal> takhfif_saghf_illness_grp { get; set; }
        public Nullable<decimal> takhfif_saghf_material_grp { get; set; }
        public Nullable<decimal> takhfif_saghf_lab_grp { get; set; }
        public Nullable<decimal> takhfif_saghf_additional_grp { get; set; }
    
        public virtual visiting visiting { get; set; }
    }
}
