//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class visit5
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public visit5()
        {
            this.visit_drug = new HashSet<visit_drug>();
            this.Visit_Lab = new HashSet<Visit_Lab>();
            this.Visit_Radio = new HashSet<Visit_Radio>();
            this.visit_shekayat = new HashSet<visit_shekayat>();
            this.visit_tashkhis = new HashSet<visit_tashkhis>();
        }
    
        public decimal KindID { get; set; }
        public Nullable<decimal> id_illness { get; set; }
        public string comment { get; set; }
        public Nullable<int> idvisit { get; set; }
        public string datevisit { get; set; }
        public string date_edit { get; set; }
        public string time_edit { get; set; }
        public Nullable<decimal> KindIDRel { get; set; }
        public Nullable<decimal> id_doctor { get; set; }
        public Nullable<byte> OKPaz { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visit_drug> visit_drug { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visit_Lab> Visit_Lab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visit_Radio> Visit_Radio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visit_shekayat> visit_shekayat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visit_tashkhis> visit_tashkhis { get; set; }
    }
}
