//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSoftClinicAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class yaraneh2
    {
        public int RuleID { get; set; }
        public int SectionID { get; set; }
        public int ID_Software { get; set; }
        public int RowID { get; set; }
        public int Code { get; set; }
        public string HeaderRule { get; set; }
        public Nullable<byte> Group12 { get; set; }
        public Nullable<int> id_illness { get; set; }
        public Nullable<int> id_visit { get; set; }
        public string date_visit { get; set; }
        public Nullable<double> Per_illness { get; set; }
        public Nullable<decimal> Mab_illness { get; set; }
        public Nullable<double> Per_Material { get; set; }
        public Nullable<decimal> Mab_Material { get; set; }
        public Nullable<double> Per_Lab { get; set; }
        public Nullable<decimal> Mab_Lab { get; set; }
        public Nullable<double> Per_Additional { get; set; }
        public Nullable<decimal> Mab_Additional { get; set; }
        public Nullable<int> id_insur { get; set; }
        public Nullable<int> id_niro { get; set; }
        public Nullable<int> id_status { get; set; }
        public Nullable<int> id_Nesbat { get; set; }
        public string D_Run { get; set; }
        public string D_Expire { get; set; }
        public Nullable<int> id_user { get; set; }
        public string date_Edit { get; set; }
        public string Time_Edit { get; set; }
        public Nullable<byte> Cancel_Flag { get; set; }
        public int Idauto { get; set; }
        public Nullable<int> CenterID { get; set; }
        public string date_delete { get; set; }
        public Nullable<int> id_userDelete { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> Freeyaraneh { get; set; }
        public Nullable<double> Per_Fani { get; set; }
        public Nullable<decimal> Mab_Fani { get; set; }
        public Nullable<double> Per_tahrir { get; set; }
        public Nullable<decimal> Mab_tahrir { get; set; }
        public Nullable<double> Per_Package { get; set; }
        public Nullable<decimal> Mab_Package { get; set; }
        public Nullable<decimal> KindidRel { get; set; }
        public Nullable<bool> ISSaghf { get; set; }
        public Nullable<decimal> Mab_Saghf { get; set; }
        public Nullable<byte> ISYaranehWith_Family { get; set; }
        public Nullable<byte> Flag_change_use_Rule { get; set; }
        public string d_run_saghf { get; set; }
        public string d_expire_saghf { get; set; }
        public Nullable<byte> check_difference { get; set; }
    
        public virtual infoCenteral infoCenteral { get; set; }
    }
}
